// Generated by build_data.py from the Macbeth text in ../bard3/mac.html
window.LINES = [
 {
  "act": "1",
  "sc": "3",
  "n": 38,
  "who": "All",
  "cue": [
   "Thrice to thine, and thrice to mine,",
   "And thrice again, to make up nine.",
   "Peace!--the charm's wound up."
  ],
  "speech": [
   {
    "l": "So foul and fair a day I have not seen."
   }
  ],
  "word": "So"
 },
 {
  "act": "1",
  "sc": "3",
  "n": 51,
  "who": "Banquo",
  "cue": [
   "Upon her skinny lips. You should be women,",
   "And yet your beards forbid me to interpret",
   "That you are so."
  ],
  "speech": [
   {
    "l": "Speak, if you can;--what are you?"
   }
  ],
  "word": "Speak"
 },
 {
  "act": "1",
  "sc": "3",
  "n": 70,
  "who": "First Witch",
  "cue": [
   "Banquo and Macbeth, all hail!"
  ],
  "speech": [
   {
    "l": "Stay, you imperfect speakers, tell me more."
   },
   {
    "l": "By Sinel's death I know I am Thane of Glamis;"
   },
   {
    "l": "But how of Cawdor? The Thane of Cawdor lives,"
   },
   {
    "l": "A prosperous gentleman; and to be king"
   },
   {
    "l": "Stands not within the prospect of belief,"
   },
   {
    "l": "No more than to be Cawdor. Say from whence"
   },
   {
    "l": "You owe this strange intelligence? or why"
   },
   {
    "l": "Upon this blasted heath you stop our way"
   },
   {
    "l": "With such prophetic greeting?--Speak, I charge you."
   }
  ],
  "word": "Stay"
 },
 {
  "act": "1",
  "sc": "3",
  "n": 81,
  "who": "Banquo",
  "cue": [
   "The earth hath bubbles, as the water has,",
   "And these are of them. Whither are they vanish'd?"
  ],
  "speech": [
   {
    "l": "Into the air; and what seem'd corporal,"
   },
   {
    "l": "Melted as breath into the wind."
   },
   {
    "l": "Would they had stay'd!"
   }
  ],
  "word": "Into"
 },
 {
  "act": "1",
  "sc": "3",
  "n": 86,
  "who": "Banquo",
  "cue": [
   "Were such things here as we do speak about?",
   "Or have we eaten on the insane root",
   "That takes the reason prisoner?"
  ],
  "speech": [
   {
    "l": "Your children shall be kings."
   }
  ],
  "word": "Your"
 },
 {
  "act": "1",
  "sc": "3",
  "n": 88,
  "who": "Banquo",
  "cue": [
   "You shall be king."
  ],
  "speech": [
   {
    "l": "And Thane of Cawdor too; went it not so?"
   }
  ],
  "word": "And"
 },
 {
  "act": "1",
  "sc": "3",
  "n": 108,
  "who": "Banquo",
  "cue": [
   "What, can the devil speak true?"
  ],
  "speech": [
   {
    "l": "The Thane of Cawdor lives: why do you dress me"
   },
   {
    "l": "In borrow'd robes?"
   }
  ],
  "word": "The"
 },
 {
  "act": "1",
  "sc": "3",
  "n": 117,
  "who": "Angus",
  "cue": [
   "He labour'd in his country's wrack, I know not;",
   "But treasons capital, confess'd and prov'd,",
   "Have overthrown him."
  ],
  "speech": [
   {
    "l": "The greatest is behind.   Thanks for your pains."
   },
   {
    "s": "To Banquo. Do you not hope your children shall be kings,"
   },
   {
    "l": "When those that gave the Thane of Cawdor to me"
   },
   {
    "l": "Promis'd no less to them?"
   }
  ],
  "word": "The"
 },
 {
  "act": "1",
  "sc": "3",
  "n": 129,
  "who": "Banquo",
  "cue": [
   "Win us with honest trifles, to betray's",
   "In deepest consequence.--",
   "Cousins, a word, I pray you."
  ],
  "speech": [
   {
    "l": "As happy prologues to the swelling act"
   },
   {
    "l": "Of the imperial theme.--I thank you, gentlemen.--"
   },
   {
    "s": "Aside. This supernatural soliciting"
   },
   {
    "l": "Cannot be ill; cannot be good. If ill,"
   },
   {
    "l": "Why hath it given me earnest of success,"
   },
   {
    "l": "Commencing in a truth? I am Thane of Cawdor:"
   },
   {
    "l": "If good, why do I yield to that suggestion"
   },
   {
    "l": "Whose horrid image doth unfix my hair,"
   },
   {
    "l": "And make my seated heart knock at my ribs,"
   },
   {
    "l": "Against the use of nature? Present fears"
   },
   {
    "l": "Are less than horrible imaginings."
   },
   {
    "l": "My thought, whose murder yet is but fantastical,"
   },
   {
    "l": "Shakes so my single state of man"
   },
   {
    "l": "That function is smother'd in surmise,"
   },
   {
    "l": "And nothing is but what is not."
   }
  ],
  "word": "As"
 },
 {
  "act": "1",
  "sc": "3",
  "n": 142,
  "who": "Banquo",
  "cue": [
   "Look, how our partner's rapt."
  ],
  "speech": [
   {
    "l": "Without my stir."
   }
  ],
  "word": "Without"
 },
 {
  "act": "1",
  "sc": "3",
  "n": 147,
  "who": "Banquo",
  "cue": [
   "New honours come upon him,",
   "Like our strange garments, cleave not to their mould",
   "But with the aid of use."
  ],
  "speech": [
   {
    "l": "Time and the hour runs through the roughest day."
   }
  ],
  "word": "Time"
 },
 {
  "act": "1",
  "sc": "3",
  "n": 149,
  "who": "Banquo",
  "cue": [
   "Worthy Macbeth, we stay upon your leisure."
  ],
  "speech": [
   {
    "l": "Give me your favour. My dull brain was wrought"
   },
   {
    "l": "With things forgotten. Kind gentlemen, your pains"
   },
   {
    "l": "Are register'd where every day I turn"
   },
   {
    "l": "The leaf to read them.--Let us toward the King.--"
   },
   {
    "l": "Think upon what hath chanc'd; and at more time,"
   },
   {
    "l": "The interim having weigh'd it, let us speak"
   },
   {
    "l": "Our free hearts each to other."
   }
  ],
  "word": "Give"
 },
 {
  "act": "1",
  "sc": "3",
  "n": 157,
  "who": "Banquo",
  "cue": [
   "Very gladly."
  ],
  "speech": [
   {
    "l": "Till then, enough.--Come, friends."
   }
  ],
  "word": "Till"
 },
 {
  "act": "1",
  "sc": "4",
  "n": 22,
  "who": "Duncan",
  "cue": [
   "That the proportion both of thanks and payment",
   "Might have been mine! only I have left to say,",
   "More is thy due than more than all can pay."
  ],
  "speech": [
   {
    "l": "The service and the loyalty I owe,"
   },
   {
    "l": "In doing it, pays itself. Your Highness' part"
   },
   {
    "l": "Is to receive our duties: and our duties"
   },
   {
    "l": "Are to your throne and state, children and servants;"
   },
   {
    "l": "Which do but what they should, by doing everything"
   },
   {
    "l": "Safe toward your love and honour."
   }
  ],
  "word": "The"
 },
 {
  "act": "1",
  "sc": "4",
  "n": 44,
  "who": "Duncan",
  "cue": [
   "But signs of nobleness, like stars, shall shine",
   "On all deservers.--From hence to Inverness,",
   "And bind us further to you."
  ],
  "speech": [
   {
    "l": "The rest is labour, which is not us'd for you:"
   },
   {
    "l": "I'll be myself the harbinger, and make joyful"
   },
   {
    "l": "The hearing of my wife with your approach;"
   },
   {
    "l": "So, humbly take my leave."
   }
  ],
  "word": "The"
 },
 {
  "act": "1",
  "sc": "4",
  "n": 49,
  "who": "Duncan",
  "cue": [
   "My worthy Cawdor!"
  ],
  "speech": [
   {
    "l": "On which I must fall down, or else o'erleap,"
   },
   {
    "l": "For in my way it lies. Stars, hide your fires!"
   },
   {
    "l": "Let not light see my black and deep desires."
   },
   {
    "l": "The eye wink at the hand, yet let that be,"
   },
   {
    "l": "Which the eye fears, when it is done, to see."
   }
  ],
  "word": "On"
 },
 {
  "act": "1",
  "sc": "5",
  "n": 58,
  "who": "Lady Macbeth",
  "cue": [
   "Thy letters have transported me beyond",
   "This ignorant present, and I feel now",
   "The future in the instant."
  ],
  "speech": [
   {
    "l": "My dearest love,"
   },
   {
    "l": "Duncan comes here tonight."
   }
  ],
  "word": "My"
 },
 {
  "act": "1",
  "sc": "5",
  "n": 61,
  "who": "Lady Macbeth",
  "cue": [
   "And when goes hence?"
  ],
  "speech": [
   {
    "l": "Tomorrow, as he purposes."
   }
  ],
  "word": "Tomorrow"
 },
 {
  "act": "1",
  "sc": "5",
  "n": 72,
  "who": "Lady Macbeth",
  "cue": [
   "This night's great business into my dispatch;",
   "Which shall to all our nights and days to come",
   "Give solely sovereign sway and masterdom."
  ],
  "speech": [
   {
    "l": "We will speak further."
   }
  ],
  "word": "We"
 },
 {
  "act": "1",
  "sc": "7",
  "n": 29,
  "who": "Lady Macbeth",
  "cue": [
   "He has almost supp'd. Why have you left the chamber?"
  ],
  "speech": [
   {
    "l": "Hath he ask'd for me?"
   }
  ],
  "word": "Hath"
 },
 {
  "act": "1",
  "sc": "7",
  "n": 31,
  "who": "Lady Macbeth",
  "cue": [
   "Know you not he has?"
  ],
  "speech": [
   {
    "l": "We will proceed no further in this business:"
   },
   {
    "l": "He hath honour'd me of late; and I have bought"
   },
   {
    "l": "Golden opinions from all sorts of people,"
   },
   {
    "l": "Which would be worn now in their newest gloss,"
   },
   {
    "l": "Not cast aside so soon."
   }
  ],
  "word": "We"
 },
 {
  "act": "1",
  "sc": "7",
  "n": 45,
  "who": "Lady Macbeth",
  "cue": [
   "And live a coward in thine own esteem,",
   "Letting \"I dare not\" wait upon \"I would,\"",
   "Like the poor cat i' th' adage?"
  ],
  "speech": [
   {
    "l": "Pr'ythee, peace!"
   },
   {
    "l": "I dare do all that may become a man;"
   },
   {
    "l": "Who dares do more is none."
   }
  ],
  "word": "Pr'ythee"
 },
 {
  "act": "1",
  "sc": "7",
  "n": 58,
  "who": "Lady Macbeth",
  "cue": [
   "Have pluck'd my nipple from his boneless gums",
   "And dash'd the brains out, had I so sworn as you",
   "Have done to this."
  ],
  "speech": [
   {
    "l": "If we should fail?"
   }
  ],
  "word": "If"
 },
 {
  "act": "1",
  "sc": "7",
  "n": 72,
  "who": "Lady Macbeth",
  "cue": [
   "Th' unguarded Duncan? what not put upon",
   "His spongy officers; who shall bear the guilt",
   "Of our great quell?"
  ],
  "speech": [
   {
    "l": "Bring forth men-children only;"
   },
   {
    "l": "For thy undaunted mettle should compose"
   },
   {
    "l": "Nothing but males. Will it not be receiv'd,"
   },
   {
    "l": "When we have mark'd with blood those sleepy two"
   },
   {
    "l": "Of his own chamber, and us'd their very daggers,"
   },
   {
    "l": "That they have done't?"
   }
  ],
  "word": "Bring"
 },
 {
  "act": "1",
  "sc": "7",
  "n": 79,
  "who": "Lady Macbeth",
  "cue": [
   "Who dares receive it other,",
   "As we shall make our griefs and clamour roar",
   "Upon his death?"
  ],
  "speech": [
   {
    "l": "I am settled, and bend up"
   },
   {
    "l": "Each corporal agent to this terrible feat."
   },
   {
    "l": "Away, and mock the time with fairest show:"
   },
   {
    "l": "False face must hide what the false heart doth know."
   }
  ],
  "word": "I"
 },
 {
  "act": "2",
  "sc": "1",
  "n": 11,
  "who": "Banquo",
  "cue": [
   "Give me my sword.--Who's there?"
  ],
  "speech": [
   {
    "l": "A friend."
   }
  ],
  "word": "A"
 },
 {
  "act": "2",
  "sc": "1",
  "n": 17,
  "who": "Banquo",
  "cue": [
   "This diamond he greets your wife withal,",
   "By the name of most kind hostess, and shut up",
   "In measureless content."
  ],
  "speech": [
   {
    "l": "Being unprepar'd,"
   },
   {
    "l": "Our will became the servant to defect,"
   },
   {
    "l": "Which else should free have wrought."
   }
  ],
  "word": "Being"
 },
 {
  "act": "2",
  "sc": "1",
  "n": 21,
  "who": "Banquo",
  "cue": [
   "All's well.",
   "I dreamt last night of the three Weird Sisters:",
   "To you they have show'd some truth."
  ],
  "speech": [
   {
    "l": "I think not of them:"
   },
   {
    "l": "Yet, when we can entreat an hour to serve,"
   },
   {
    "l": "We would spend it in some words upon that business,"
   },
   {
    "l": "If you would grant the time."
   }
  ],
  "word": "I"
 },
 {
  "act": "2",
  "sc": "1",
  "n": 25,
  "who": "Banquo",
  "cue": [
   "At your kind'st leisure."
  ],
  "speech": [
   {
    "l": "If you shall cleave to my consent, when 'tis,"
   },
   {
    "l": "It shall make honour for you."
   }
  ],
  "word": "If"
 },
 {
  "act": "2",
  "sc": "1",
  "n": 29,
  "who": "Banquo",
  "cue": [
   "In seeking to augment it, but still keep",
   "My bosom franchis'd, and allegiance clear,",
   "I shall be counsell'd."
  ],
  "speech": [
   {
    "l": "Good repose the while!"
   }
  ],
  "word": "Good"
 },
 {
  "act": "2",
  "sc": "1",
  "n": 31,
  "who": "Banquo",
  "cue": [
   "Thanks, sir: the like to you."
  ],
  "speech": [
   {
    "l": "Go bid thy mistress, when my drink is ready,"
   },
   {
    "l": "She strike upon the bell. Get thee to bed."
   },
   {
    "s": "Exit Servant."
   },
   {
    "l": "Is this a dagger which I see before me,"
   },
   {
    "l": "The handle toward my hand? Come, let me clutch thee:--"
   },
   {
    "l": "I have thee not, and yet I see thee still."
   },
   {
    "l": "Art thou not, fatal vision, sensible"
   },
   {
    "l": "To feeling as to sight? or art thou but"
   },
   {
    "l": "A dagger of the mind, a false creation,"
   },
   {
    "l": "Proceeding from the heat-oppressed brain?"
   },
   {
    "l": "I see thee yet, in form as palpable"
   },
   {
    "l": "As this which now I draw."
   },
   {
    "l": "Thou marshall'st me the way that I was going;"
   },
   {
    "l": "And such an instrument I was to use."
   },
   {
    "l": "Mine eyes are made the fools o' the other senses,"
   },
   {
    "l": "Or else worth all the rest: I see thee still;"
   },
   {
    "l": "And on thy blade and dudgeon, gouts of blood,"
   },
   {
    "l": "Which was not so before.--There's no such thing."
   },
   {
    "l": "It is the bloody business which informs"
   },
   {
    "l": "Thus to mine eyes.--Now o'er the one half-world"
   },
   {
    "l": "Nature seems dead, and wicked dreams abuse"
   },
   {
    "l": "The curtain'd sleep. Witchcraft celebrates"
   },
   {
    "l": "Pale Hecate's off'rings; and wither'd murder,"
   },
   {
    "s": "Alarum'd by his sentinel, the wolf,"
   },
   {
    "l": "Whose howl's his watch, thus with his stealthy pace,"
   },
   {
    "l": "With Tarquin's ravishing strides, towards his design"
   },
   {
    "l": "Moves like a ghost.--Thou sure and firm-set earth,"
   },
   {
    "l": "Hear not my steps, which way they walk, for fear"
   },
   {
    "l": "Thy very stones prate of my whereabout,"
   },
   {
    "l": "And take the present horror from the time,"
   },
   {
    "l": "Which now suits with it.--Whiles I threat, he lives."
   },
   {
    "l": "Words to the heat of deeds too cold breath gives."
   },
   {
    "s": "A bell rings."
   },
   {
    "l": "I go, and it is done. The bell invites me."
   },
   {
    "l": "Hear it not, Duncan, for it is a knell"
   },
   {
    "l": "That summons thee to heaven or to hell."
   }
  ],
  "word": "Go"
 },
 {
  "act": "2",
  "sc": "2",
  "n": 11,
  "who": "Lady Macbeth",
  "cue": [
   "Confounds us.--Hark!--I laid their daggers ready;",
   "He could not miss 'em.--Had he not resembled",
   "My father as he slept, I had done't.--My husband!"
  ],
  "speech": [
   {
    "l": "I have done the deed.--Didst thou not hear a noise?"
   }
  ],
  "word": "I"
 },
 {
  "act": "2",
  "sc": "2",
  "n": 14,
  "who": "Lady Macbeth",
  "cue": [
   "I heard the owl scream and the crickets cry.",
   "Did not you speak?"
  ],
  "speech": [
   {
    "l": "When?"
   }
  ],
  "word": "When"
 },
 {
  "act": "2",
  "sc": "2",
  "n": 17,
  "who": "Lady Macbeth",
  "cue": [
   "Now."
  ],
  "speech": [
   {
    "l": "As I descended?"
   }
  ],
  "word": "As"
 },
 {
  "act": "2",
  "sc": "2",
  "n": 19,
  "who": "Lady Macbeth",
  "cue": [
   "Ay."
  ],
  "speech": [
   {
    "l": "Hark!--Who lies i' th' second chamber?"
   }
  ],
  "word": "Hark"
 },
 {
  "act": "2",
  "sc": "2",
  "n": 21,
  "who": "Lady Macbeth",
  "cue": [
   "Donalbain."
  ],
  "speech": [
   {
    "l": "This is a sorry sight."
   }
  ],
  "word": "This"
 },
 {
  "act": "2",
  "sc": "2",
  "n": 22,
  "who": "Lady Macbeth",
  "cue": [
   "A foolish thought, to say a sorry sight."
  ],
  "speech": [
   {
    "l": "There's one did laugh in's sleep, and one cried, \"Murder!\""
   },
   {
    "l": "That they did wake each other: I stood and heard them."
   },
   {
    "l": "But they did say their prayers, and address'd them"
   },
   {
    "l": "Again to sleep."
   }
  ],
  "word": "There's"
 },
 {
  "act": "2",
  "sc": "2",
  "n": 27,
  "who": "Lady Macbeth",
  "cue": [
   "There are two lodg'd together."
  ],
  "speech": [
   {
    "l": "One cried, \"God bless us!\" and, \"Amen,\" the other,"
   },
   {
    "l": "As they had seen me with these hangman's hands."
   },
   {
    "l": "List'ning their fear, I could not say \"Amen,\""
   },
   {
    "l": "When they did say, \"God bless us.\""
   }
  ],
  "word": "One"
 },
 {
  "act": "2",
  "sc": "2",
  "n": 31,
  "who": "Lady Macbeth",
  "cue": [
   "Consider it not so deeply."
  ],
  "speech": [
   {
    "l": "But wherefore could not I pronounce \"Amen\"?"
   },
   {
    "l": "I had most need of blessing, and \"Amen\""
   },
   {
    "l": "Stuck in my throat."
   }
  ],
  "word": "But"
 },
 {
  "act": "2",
  "sc": "2",
  "n": 35,
  "who": "Lady Macbeth",
  "cue": [
   "These deeds must not be thought",
   "After these ways; so, it will make us mad."
  ],
  "speech": [
   {
    "l": "Methought I heard a voice cry, \"Sleep no more!"
   },
   {
    "l": "Macbeth does murder sleep,\"--the innocent sleep;"
   },
   {
    "l": "Sleep that knits up the ravell'd sleave of care,"
   },
   {
    "l": "The death of each day's life, sore labour's bath,"
   },
   {
    "l": "Balm of hurt minds, great nature's second course,"
   },
   {
    "l": "Chief nourisher in life's feast."
   }
  ],
  "word": "Methought"
 },
 {
  "act": "2",
  "sc": "2",
  "n": 40,
  "who": "Lady Macbeth",
  "cue": [
   "What do you mean?"
  ],
  "speech": [
   {
    "l": "Still it cried, \"Sleep no more!\" to all the house:"
   },
   {
    "l": "\"Glamis hath murder'd sleep, and therefore Cawdor"
   },
   {
    "l": "Shall sleep no more. Macbeth shall sleep no more!\""
   }
  ],
  "word": "Still"
 },
 {
  "act": "2",
  "sc": "2",
  "n": 50,
  "who": "Lady Macbeth",
  "cue": [
   "Why did you bring these daggers from the place?",
   "They must lie there: go carry them, and smear",
   "The sleepy grooms with blood."
  ],
  "speech": [
   {
    "l": "I'll go no more:"
   },
   {
    "l": "I am afraid to think what I have done;"
   },
   {
    "l": "Look on't again I dare not."
   }
  ],
  "word": "I'll"
 },
 {
  "act": "2",
  "sc": "2",
  "n": 58,
  "who": "Lady Macbeth",
  "cue": [
   "That fears a painted devil. If he do bleed,",
   "I'll gild the faces of the grooms withal,",
   "For it must seem their guilt."
  ],
  "speech": [
   {
    "l": "Whence is that knocking?"
   },
   {
    "l": "How is't with me, when every noise appals me?"
   },
   {
    "l": "What hands are here? Ha, they pluck out mine eyes!"
   },
   {
    "l": "Will all great Neptune's ocean wash this blood"
   },
   {
    "l": "Clean from my hand? No, this my hand will rather"
   },
   {
    "l": "The multitudinous seas incarnadine,"
   },
   {
    "l": "Making the green one red."
   }
  ],
  "word": "Whence"
 },
 {
  "act": "2",
  "sc": "2",
  "n": 73,
  "who": "Lady Macbeth",
  "cue": [
   "Get on your nightgown, lest occasion call us",
   "And show us to be watchers. Be not lost",
   "So poorly in your thoughts."
  ],
  "speech": [
   {
    "l": "To know my deed, 'twere best not know myself."
   },
   {
    "l": "Wake Duncan with thy knocking! I would thou couldst!"
   }
  ],
  "word": "To"
 },
 {
  "act": "2",
  "sc": "3",
  "n": 48,
  "who": "Lennox",
  "cue": [
   "Good morrow, noble sir!"
  ],
  "speech": [
   {
    "l": "Good morrow, both!"
   }
  ],
  "word": "Good"
 },
 {
  "act": "2",
  "sc": "3",
  "n": 50,
  "who": "Macduff",
  "cue": [
   "Is the King stirring, worthy thane?"
  ],
  "speech": [
   {
    "l": "Not yet."
   }
  ],
  "word": "Not"
 },
 {
  "act": "2",
  "sc": "3",
  "n": 52,
  "who": "Macduff",
  "cue": [
   "He did command me to call timely on him.",
   "I have almost slipp'd the hour."
  ],
  "speech": [
   {
    "l": "I'll bring you to him."
   }
  ],
  "word": "I'll"
 },
 {
  "act": "2",
  "sc": "3",
  "n": 55,
  "who": "Macduff",
  "cue": [
   "I know this is a joyful trouble to you;",
   "But yet 'tis one."
  ],
  "speech": [
   {
    "l": "The labour we delight in physics pain."
   },
   {
    "l": "This is the door."
   }
  ],
  "word": "The"
 },
 {
  "act": "2",
  "sc": "3",
  "n": 58,
  "who": "Lennox",
  "cue": [
   "Goes the King hence today?"
  ],
  "speech": [
   {
    "l": "He does. He did appoint so."
   }
  ],
  "word": "He"
 },
 {
  "act": "2",
  "sc": "3",
  "n": 66,
  "who": "Lennox",
  "cue": [
   "New hatch'd to the woeful time. The obscure bird",
   "Clamour'd the live-long night. Some say the earth",
   "Was feverous, and did shake."
  ],
  "speech": [
   {
    "l": "'Twas a rough night."
   }
  ],
  "word": "'Twas"
 },
 {
  "act": "2",
  "sc": "3",
  "n": 74,
  "who": "Macduff",
  "cue": [
   "Most sacrilegious murder hath broke ope",
   "The Lord's anointed temple, and stole thence",
   "The life o' th' building."
  ],
  "speech": [
   {
    "l": "What is't you say? the life?"
   }
  ],
  "word": "What"
 },
 {
  "act": "2",
  "sc": "3",
  "n": 97,
  "who": "Banquo",
  "cue": [
   "Too cruel anywhere.--",
   "Dear Duff, I pr'ythee, contradict thyself,",
   "And say it is not so."
  ],
  "speech": [
   {
    "l": "Had I but died an hour before this chance,"
   },
   {
    "l": "I had liv'd a blessed time; for, from this instant"
   },
   {
    "l": "There's nothing serious in mortality."
   },
   {
    "l": "All is but toys: renown and grace is dead;"
   },
   {
    "l": "The wine of life is drawn, and the mere lees"
   },
   {
    "l": "Is left this vault to brag of."
   }
  ],
  "word": "Had"
 },
 {
  "act": "2",
  "sc": "3",
  "n": 102,
  "who": "Donalbain",
  "cue": [
   "What is amiss?"
  ],
  "speech": [
   {
    "l": "You are, and do not know't:"
   },
   {
    "l": "The spring, the head, the fountain of your blood"
   },
   {
    "l": "Is stopp'd; the very source of it is stopp'd."
   }
  ],
  "word": "You"
 },
 {
  "act": "2",
  "sc": "3",
  "n": 111,
  "who": "Lennox",
  "cue": [
   "So were their daggers, which, unwip'd, we found",
   "Upon their pillows. They star'd, and were distracted;",
   "No man's life was to be trusted with them."
  ],
  "speech": [
   {
    "l": "O, yet I do repent me of my fury,"
   },
   {
    "l": "That I did kill them."
   }
  ],
  "word": "O"
 },
 {
  "act": "2",
  "sc": "3",
  "n": 114,
  "who": "Macduff",
  "cue": [
   "Wherefore did you so?"
  ],
  "speech": [
   {
    "l": "Who can be wise, amaz'd, temperate, and furious,"
   },
   {
    "l": "Loyal and neutral, in a moment? No man:"
   },
   {
    "l": "Th' expedition of my violent love"
   },
   {
    "l": "Outrun the pauser, reason. Here lay Duncan,"
   },
   {
    "l": "His silver skin lac'd with his golden blood;"
   },
   {
    "l": "And his gash'd stabs look'd like a breach in nature"
   },
   {
    "l": "For ruin's wasteful entrance: there, the murderers,"
   },
   {
    "l": "Steep'd in the colours of their trade, their daggers"
   },
   {
    "l": "Unmannerly breech'd with gore. Who could refrain,"
   },
   {
    "l": "That had a heart to love, and in that heart"
   },
   {
    "l": "Courage to make's love known?"
   }
  ],
  "word": "Who"
 },
 {
  "act": "2",
  "sc": "3",
  "n": 139,
  "who": "All",
  "cue": [
   "So all."
  ],
  "speech": [
   {
    "l": "Let's briefly put on manly readiness,"
   },
   {
    "l": "And meet i' th' hall together."
   }
  ],
  "word": "Let's"
 },
 {
  "act": "3",
  "sc": "1",
  "n": 10,
  "who": "Banquo",
  "cue": [
   "Why, by the verities on thee made good,",
   "May they not be my oracles as well,",
   "And set me up in hope? But hush; no more."
  ],
  "speech": [
   {
    "l": "Here's our chief guest."
   }
  ],
  "word": "Here's"
 },
 {
  "act": "3",
  "sc": "1",
  "n": 14,
  "who": "Lady Macbeth",
  "cue": [
   "If he had been forgotten,",
   "It had been as a gap in our great feast,",
   "And all-thing unbecoming."
  ],
  "speech": [
   {
    "l": "Tonight we hold a solemn supper, sir,"
   },
   {
    "l": "And I'll request your presence."
   }
  ],
  "word": "Tonight"
 },
 {
  "act": "3",
  "sc": "1",
  "n": 19,
  "who": "Banquo",
  "cue": [
   "Command upon me, to the which my duties",
   "Are with a most indissoluble tie",
   "For ever knit."
  ],
  "speech": [
   {
    "l": "Ride you this afternoon?"
   }
  ],
  "word": "Ride"
 },
 {
  "act": "3",
  "sc": "1",
  "n": 21,
  "who": "Banquo",
  "cue": [
   "Ay, my good lord."
  ],
  "speech": [
   {
    "l": "We should have else desir'd your good advice"
   },
   {
    "l": "(Which still hath been both grave and prosperous)"
   },
   {
    "l": "In this day's council; but we'll take tomorrow."
   },
   {
    "l": "Is't far you ride?"
   }
  ],
  "word": "We"
 },
 {
  "act": "3",
  "sc": "1",
  "n": 28,
  "who": "Banquo",
  "cue": [
   "'Twixt this and supper: go not my horse the better,",
   "I must become a borrower of the night,",
   "For a dark hour or twain."
  ],
  "speech": [
   {
    "l": "Fail not our feast."
   }
  ],
  "word": "Fail"
 },
 {
  "act": "3",
  "sc": "1",
  "n": 30,
  "who": "Banquo",
  "cue": [
   "My lord, I will not."
  ],
  "speech": [
   {
    "l": "We hear our bloody cousins are bestow'd"
   },
   {
    "l": "In England and in Ireland; not confessing"
   },
   {
    "l": "Their cruel parricide, filling their hearers"
   },
   {
    "l": "With strange invention. But of that tomorrow,"
   },
   {
    "l": "When therewithal we shall have cause of state"
   },
   {
    "l": "Craving us jointly. Hie you to horse: adieu,"
   },
   {
    "l": "Till you return at night. Goes Fleance with you?"
   }
  ],
  "word": "We"
 },
 {
  "act": "3",
  "sc": "1",
  "n": 39,
  "who": "Banquo",
  "cue": [
   "Ay, my good lord: our time does call upon's."
  ],
  "speech": [
   {
    "l": "I wish your horses swift and sure of foot;"
   },
   {
    "l": "And so I do commend you to their backs."
   },
   {
    "l": "Farewell.--"
   },
   {
    "s": "Exit Banquo."
   },
   {
    "l": "Let every man be master of his time"
   },
   {
    "l": "Till seven at night; to make society"
   },
   {
    "l": "The sweeter welcome, we will keep ourself"
   },
   {
    "l": "Till supper time alone: while then, God be with you."
   },
   {
    "s": "Exeunt Lady Macbeth, Lords, &c."
   },
   {
    "l": "Sirrah, a word with you. Attend those men"
   },
   {
    "l": "Our pleasure?"
   }
  ],
  "word": "I"
 },
 {
  "act": "3",
  "sc": "1",
  "n": 48,
  "who": "Servant",
  "cue": [
   "They are, my lord, without the palace gate."
  ],
  "speech": [
   {
    "l": "Bring them before us."
   },
   {
    "s": "Exit Servant."
   },
   {
    "l": "To be thus is nothing,"
   },
   {
    "l": "But to be safely thus. Our fears in Banquo"
   },
   {
    "l": "Stick deep, and in his royalty of nature"
   },
   {
    "l": "Reigns that which would be fear'd: 'tis much he dares;"
   },
   {
    "l": "And, to that dauntless temper of his mind,"
   },
   {
    "l": "He hath a wisdom that doth guide his valour"
   },
   {
    "l": "To act in safety. There is none but he"
   },
   {
    "l": "Whose being I do fear: and under him"
   },
   {
    "l": "My genius is rebuk'd; as, it is said,"
   },
   {
    "l": "Mark Antony's was by Caesar. He chid the sisters"
   },
   {
    "l": "When first they put the name of king upon me,"
   },
   {
    "l": "And bade them speak to him; then, prophet-like,"
   },
   {
    "l": "They hail'd him father to a line of kings:"
   },
   {
    "l": "Upon my head they plac'd a fruitless crown,"
   },
   {
    "l": "And put a barren sceptre in my gripe,"
   },
   {
    "l": "Thence to be wrench'd with an unlineal hand,"
   },
   {
    "l": "No son of mine succeeding. If't be so,"
   },
   {
    "l": "For Banquo's issue have I fil'd my mind;"
   },
   {
    "l": "For them the gracious Duncan have I murder'd;"
   },
   {
    "l": "Put rancours in the vessel of my peace"
   },
   {
    "l": "Only for them; and mine eternal jewel"
   },
   {
    "l": "Given to the common enemy of man,"
   },
   {
    "l": "To make them kings, the seed of Banquo kings!"
   },
   {
    "l": "Rather than so, come, fate, into the list,"
   },
   {
    "l": "And champion me to th' utterance!--Who's there?--"
   },
   {
    "s": "Enter Servant with two Murderers."
   },
   {
    "l": "Now go to the door, and stay there till we call."
   },
   {
    "s": "Exit Servant."
   },
   {
    "l": "Was it not yesterday we spoke together?"
   }
  ],
  "word": "Bring"
 },
 {
  "act": "3",
  "sc": "1",
  "n": 75,
  "who": "First Murderer",
  "cue": [
   "It was, so please your Highness."
  ],
  "speech": [
   {
    "l": "Well then, now"
   },
   {
    "l": "Have you consider'd of my speeches? Know"
   },
   {
    "l": "That it was he, in the times past, which held you"
   },
   {
    "l": "So under fortune, which you thought had been"
   },
   {
    "l": "Our innocent self? This I made good to you"
   },
   {
    "l": "In our last conference, pass'd in probation with you"
   },
   {
    "l": "How you were borne in hand, how cross'd, the instruments,"
   },
   {
    "l": "Who wrought with them, and all things else that might"
   },
   {
    "l": "To half a soul and to a notion craz'd"
   },
   {
    "l": "Say, \"Thus did Banquo.\""
   }
  ],
  "word": "Well"
 },
 {
  "act": "3",
  "sc": "1",
  "n": 85,
  "who": "First Murderer",
  "cue": [
   "You made it known to us."
  ],
  "speech": [
   {
    "l": "I did so; and went further, which is now"
   },
   {
    "l": "Our point of second meeting. Do you find"
   },
   {
    "l": "Your patience so predominant in your nature,"
   },
   {
    "l": "That you can let this go? Are you so gospell'd,"
   },
   {
    "l": "To pray for this good man and for his issue,"
   },
   {
    "l": "Whose heavy hand hath bow'd you to the grave,"
   },
   {
    "l": "And beggar'd yours forever?"
   }
  ],
  "word": "I"
 },
 {
  "act": "3",
  "sc": "1",
  "n": 91,
  "who": "First Murderer",
  "cue": [
   "We are men, my liege."
  ],
  "speech": [
   {
    "l": "Ay, in the catalogue ye go for men;"
   },
   {
    "l": "As hounds, and greyhounds, mongrels, spaniels, curs,"
   },
   {
    "l": "Shoughs, water-rugs, and demi-wolves are clept"
   },
   {
    "l": "All by the name of dogs: the valu'd file"
   },
   {
    "l": "Distinguishes the swift, the slow, the subtle,"
   },
   {
    "l": "The housekeeper, the hunter, every one"
   },
   {
    "l": "According to the gift which bounteous nature"
   },
   {
    "l": "Hath in him clos'd; whereby he does receive"
   },
   {
    "l": "Particular addition, from the bill"
   },
   {
    "l": "That writes them all alike: and so of men."
   },
   {
    "l": "Now, if you have a station in the file,"
   },
   {
    "l": "Not i' th' worst rank of manhood, say't;"
   },
   {
    "l": "And I will put that business in your bosoms,"
   },
   {
    "l": "Whose execution takes your enemy off,"
   },
   {
    "l": "Grapples you to the heart and love of us,"
   },
   {
    "l": "Who wear our health but sickly in his life,"
   },
   {
    "l": "Which in his death were perfect."
   }
  ],
  "word": "Ay"
 },
 {
  "act": "3",
  "sc": "1",
  "n": 115,
  "who": "First Murderer",
  "cue": [
   "So weary with disasters, tugg'd with fortune,",
   "That I would set my life on any chance,",
   "To mend it or be rid on't."
  ],
  "speech": [
   {
    "l": "Both of you"
   },
   {
    "l": "Know Banquo was your enemy."
   }
  ],
  "word": "Both"
 },
 {
  "act": "3",
  "sc": "1",
  "n": 117,
  "who": "Both Murderers",
  "cue": [
   "True, my lord."
  ],
  "speech": [
   {
    "l": "So is he mine; and in such bloody distance,"
   },
   {
    "l": "That every minute of his being thrusts"
   },
   {
    "l": "Against my near'st of life; and though I could"
   },
   {
    "l": "With barefac'd power sweep him from my sight,"
   },
   {
    "l": "And bid my will avouch it, yet I must not,"
   },
   {
    "l": "For certain friends that are both his and mine,"
   },
   {
    "l": "Whose loves I may not drop, but wail his fall"
   },
   {
    "l": "Who I myself struck down: and thence it is"
   },
   {
    "l": "That I to your assistance do make love,"
   },
   {
    "l": "Masking the business from the common eye"
   },
   {
    "l": "For sundry weighty reasons."
   }
  ],
  "word": "So"
 },
 {
  "act": "3",
  "sc": "1",
  "n": 128,
  "who": "First Murderer",
  "cue": [
   "Though our lives--"
  ],
  "speech": [
   {
    "l": "Your spirits shine through you. Within this hour at most,"
   },
   {
    "l": "I will advise you where to plant yourselves,"
   },
   {
    "l": "Acquaint you with the perfect spy o' th' time,"
   },
   {
    "l": "The moment on't; for't must be done tonight"
   },
   {
    "l": "And something from the palace; always thought"
   },
   {
    "l": "That I require a clearness. And with him"
   },
   {
    "l": "(To leave no rubs nor botches in the work)"
   },
   {
    "l": "Fleance his son, that keeps him company,"
   },
   {
    "l": "Whose absence is no less material to me"
   },
   {
    "l": "Than is his father's, must embrace the fate"
   },
   {
    "l": "Of that dark hour. Resolve yourselves apart."
   },
   {
    "l": "I'll come to you anon."
   }
  ],
  "word": "Your"
 },
 {
  "act": "3",
  "sc": "1",
  "n": 140,
  "who": "Both Murderers",
  "cue": [
   "We are resolv'd, my lord."
  ],
  "speech": [
   {
    "l": "I'll call upon you straight: abide within."
   },
   {
    "s": "Exeunt Murderers."
   },
   {
    "l": "It is concluded. Banquo, thy soul's flight,"
   },
   {
    "l": "If it find heaven, must find it out tonight."
   }
  ],
  "word": "I'll"
 },
 {
  "act": "3",
  "sc": "2",
  "n": 13,
  "who": "Lady Macbeth",
  "cue": [
   "Using those thoughts which should indeed have died",
   "With them they think on? Things without all remedy",
   "Should be without regard: what's done is done."
  ],
  "speech": [
   {
    "l": "We have scorch'd the snake, not kill'd it."
   },
   {
    "l": "She'll close, and be herself; whilst our poor malice"
   },
   {
    "l": "Remains in danger of her former tooth."
   },
   {
    "l": "But let the frame of things disjoint,"
   },
   {
    "l": "Both the worlds suffer,"
   },
   {
    "l": "Ere we will eat our meal in fear, and sleep"
   },
   {
    "l": "In the affliction of these terrible dreams"
   },
   {
    "l": "That shake us nightly. Better be with the dead,"
   },
   {
    "l": "Whom we, to gain our peace, have sent to peace,"
   },
   {
    "l": "Than on the torture of the mind to lie"
   },
   {
    "l": "In restless ecstasy. Duncan is in his grave;"
   },
   {
    "l": "After life's fitful fever he sleeps well;"
   },
   {
    "l": "Treason has done his worst: nor steel, nor poison,"
   },
   {
    "l": "Malice domestic, foreign levy, nothing"
   },
   {
    "l": "Can touch him further."
   }
  ],
  "word": "We"
 },
 {
  "act": "3",
  "sc": "2",
  "n": 29,
  "who": "Lady Macbeth",
  "cue": [
   "Come on,",
   "Gently my lord, sleek o'er your rugged looks;",
   "Be bright and jovial among your guests tonight."
  ],
  "speech": [
   {
    "l": "So shall I, love; and so, I pray, be you."
   },
   {
    "l": "Let your remembrance apply to Banquo;"
   },
   {
    "l": "Present him eminence, both with eye and tongue:"
   },
   {
    "l": "Unsafe the while, that we"
   },
   {
    "l": "Must lave our honours in these flattering streams,"
   },
   {
    "l": "And make our faces vizards to our hearts,"
   },
   {
    "l": "Disguising what they are."
   }
  ],
  "word": "So"
 },
 {
  "act": "3",
  "sc": "2",
  "n": 36,
  "who": "Lady Macbeth",
  "cue": [
   "You must leave this."
  ],
  "speech": [
   {
    "l": "O, full of scorpions is my mind, dear wife!"
   },
   {
    "l": "Thou know'st that Banquo, and his Fleance, lives."
   }
  ],
  "word": "O"
 },
 {
  "act": "3",
  "sc": "2",
  "n": 39,
  "who": "Lady Macbeth",
  "cue": [
   "But in them nature's copy's not eterne."
  ],
  "speech": [
   {
    "l": "There's comfort yet; they are assailable."
   },
   {
    "l": "Then be thou jocund. Ere the bat hath flown"
   },
   {
    "l": "His cloister'd flight, ere to black Hecate's summons"
   },
   {
    "l": "The shard-born beetle, with his drowsy hums,"
   },
   {
    "l": "Hath rung night's yawning peal, there shall be done"
   },
   {
    "l": "A deed of dreadful note."
   }
  ],
  "word": "There's"
 },
 {
  "act": "3",
  "sc": "2",
  "n": 45,
  "who": "Lady Macbeth",
  "cue": [
   "What's to be done?"
  ],
  "speech": [
   {
    "l": "Be innocent of the knowledge, dearest chuck,"
   },
   {
    "l": "Till thou applaud the deed. Come, seeling night,"
   },
   {
    "l": "Scarf up the tender eye of pitiful day,"
   },
   {
    "l": "And with thy bloody and invisible hand"
   },
   {
    "l": "Cancel and tear to pieces that great bond"
   },
   {
    "l": "Which keeps me pale!--Light thickens; and the crow"
   },
   {
    "l": "Makes wing to th' rooky wood."
   },
   {
    "l": "Good things of day begin to droop and drowse,"
   },
   {
    "l": "Whiles night's black agents to their preys do rouse."
   },
   {
    "l": "Thou marvell'st at my words: but hold thee still;"
   },
   {
    "l": "Things bad begun make strong themselves by ill."
   },
   {
    "l": "So, pr'ythee, go with me."
   }
  ],
  "word": "Be"
 },
 {
  "act": "3",
  "sc": "4",
  "n": 4,
  "who": "Lords",
  "cue": [
   "Thanks to your Majesty."
  ],
  "speech": [
   {
    "l": "Ourself will mingle with society,"
   },
   {
    "l": "And play the humble host."
   },
   {
    "l": "Our hostess keeps her state; but, in best time,"
   },
   {
    "l": "We will require her welcome."
   }
  ],
  "word": "Ourself"
 },
 {
  "act": "3",
  "sc": "4",
  "n": 9,
  "who": "Lady Macbeth",
  "cue": [
   "Pronounce it for me, sir, to all our friends;",
   "For my heart speaks they are welcome."
  ],
  "speech": [
   {
    "l": "See, they encounter thee with their hearts' thanks."
   },
   {
    "l": "Both sides are even: here I'll sit i' th' midst."
   },
   {
    "l": "Be large in mirth; anon we'll drink a measure"
   },
   {
    "l": "The table round. There's blood upon thy face."
   }
  ],
  "word": "See"
 },
 {
  "act": "3",
  "sc": "4",
  "n": 14,
  "who": "Murderer",
  "cue": [
   "'Tis Banquo's then."
  ],
  "speech": [
   {
    "l": "'Tis better thee without than he within."
   },
   {
    "l": "Is he dispatch'd?"
   }
  ],
  "word": "'Tis"
 },
 {
  "act": "3",
  "sc": "4",
  "n": 16,
  "who": "Murderer",
  "cue": [
   "My lord, his throat is cut. That I did for him."
  ],
  "speech": [
   {
    "l": "Thou art the best o' th' cut-throats;"
   },
   {
    "l": "Yet he's good that did the like for Fleance:"
   },
   {
    "l": "If thou didst it, thou art the nonpareil."
   }
  ],
  "word": "Thou"
 },
 {
  "act": "3",
  "sc": "4",
  "n": 21,
  "who": "Murderer",
  "cue": [
   "Most royal sir,",
   "Fleance is 'scap'd."
  ],
  "speech": [
   {
    "l": "Then comes my fit again: I had else been perfect;"
   },
   {
    "l": "Whole as the marble, founded as the rock,"
   },
   {
    "l": "As broad and general as the casing air:"
   },
   {
    "l": "But now I am cabin'd, cribb'd, confin'd, bound in"
   },
   {
    "l": "To saucy doubts and fears. But Banquo's safe?"
   }
  ],
  "word": "Then"
 },
 {
  "act": "3",
  "sc": "4",
  "n": 28,
  "who": "Murderer",
  "cue": [
   "Ay, my good lord. Safe in a ditch he bides,",
   "With twenty trenched gashes on his head;",
   "The least a death to nature."
  ],
  "speech": [
   {
    "l": "Thanks for that."
   },
   {
    "l": "There the grown serpent lies; the worm that's fled"
   },
   {
    "l": "Hath nature that in time will venom breed,"
   },
   {
    "l": "No teeth for th' present.--Get thee gone; tomorrow"
   },
   {
    "l": "We'll hear, ourselves, again."
   }
  ],
  "word": "Thanks"
 },
 {
  "act": "3",
  "sc": "4",
  "n": 37,
  "who": "Lady Macbeth",
  "cue": [
   "'Tis given with welcome. To feed were best at home;",
   "From thence the sauce to meat is ceremony;",
   "Meeting were bare without it."
  ],
  "speech": [
   {
    "l": "Sweet remembrancer!--"
   },
   {
    "l": "Now, good digestion wait on appetite,"
   },
   {
    "l": "And health on both!"
   }
  ],
  "word": "Sweet"
 },
 {
  "act": "3",
  "sc": "4",
  "n": 40,
  "who": "Lennox",
  "cue": [
   "May't please your Highness sit."
  ],
  "speech": [
   {
    "l": "Here had we now our country's honour roof'd,"
   },
   {
    "l": "Were the grac'd person of our Banquo present;"
   },
   {
    "l": "Who may I rather challenge for unkindness"
   },
   {
    "l": "Than pity for mischance!"
   }
  ],
  "word": "Here"
 },
 {
  "act": "3",
  "sc": "4",
  "n": 45,
  "who": "Ross",
  "cue": [
   "His absence, sir,",
   "Lays blame upon his promise. Please't your Highness",
   "To grace us with your royal company?"
  ],
  "speech": [
   {
    "l": "The table's full."
   }
  ],
  "word": "The"
 },
 {
  "act": "3",
  "sc": "4",
  "n": 47,
  "who": "Lennox",
  "cue": [
   "Here is a place reserv'd, sir."
  ],
  "speech": [
   {
    "l": "Where?"
   }
  ],
  "word": "Where"
 },
 {
  "act": "3",
  "sc": "4",
  "n": 48,
  "who": "Lennox",
  "cue": [
   "Here, my good lord. What is't that moves your Highness?"
  ],
  "speech": [
   {
    "l": "Which of you have done this?"
   }
  ],
  "word": "Which"
 },
 {
  "act": "3",
  "sc": "4",
  "n": 50,
  "who": "Lords",
  "cue": [
   "What, my good lord?"
  ],
  "speech": [
   {
    "l": "Thou canst not say I did it. Never shake"
   },
   {
    "l": "Thy gory locks at me."
   }
  ],
  "word": "Thou"
 },
 {
  "act": "3",
  "sc": "4",
  "n": 58,
  "who": "Lady Macbeth",
  "cue": [
   "He will again be well. If much you note him,",
   "You shall offend him, and extend his passion.",
   "Feed, and regard him not.--Are you a man?"
  ],
  "speech": [
   {
    "l": "Ay, and a bold one, that dare look on that"
   },
   {
    "l": "Which might appal the devil."
   }
  ],
  "word": "Ay"
 },
 {
  "act": "3",
  "sc": "4",
  "n": 68,
  "who": "Lady Macbeth",
  "cue": [
   "Authoris'd by her grandam. Shame itself!",
   "Why do you make such faces? When all's done,",
   "You look but on a stool."
  ],
  "speech": [
   {
    "l": "Pr'ythee, see there!"
   },
   {
    "l": "Behold! look! lo! how say you?"
   },
   {
    "l": "Why, what care I? If thou canst nod, speak too.--"
   },
   {
    "l": "If charnel houses and our graves must send"
   },
   {
    "l": "Those that we bury back, our monuments"
   },
   {
    "l": "Shall be the maws of kites."
   }
  ],
  "word": "Pr'ythee"
 },
 {
  "act": "3",
  "sc": "4",
  "n": 74,
  "who": "Lady Macbeth",
  "cue": [
   "What, quite unmann'd in folly?"
  ],
  "speech": [
   {
    "l": "If I stand here, I saw him."
   }
  ],
  "word": "If"
 },
 {
  "act": "3",
  "sc": "4",
  "n": 76,
  "who": "Lady Macbeth",
  "cue": [
   "Fie, for shame!"
  ],
  "speech": [
   {
    "l": "Blood hath been shed ere now, i' th' olden time,"
   },
   {
    "l": "Ere humane statute purg'd the gentle weal;"
   },
   {
    "l": "Ay, and since too, murders have been perform'd"
   },
   {
    "l": "Too terrible for the ear: the time has been,"
   },
   {
    "l": "That, when the brains were out, the man would die,"
   },
   {
    "l": "And there an end; but now they rise again,"
   },
   {
    "l": "With twenty mortal murders on their crowns,"
   },
   {
    "l": "And push us from our stools. This is more strange"
   },
   {
    "l": "Than such a murder is."
   }
  ],
  "word": "Blood"
 },
 {
  "act": "3",
  "sc": "4",
  "n": 85,
  "who": "Lady Macbeth",
  "cue": [
   "My worthy lord,",
   "Your noble friends do lack you."
  ],
  "speech": [
   {
    "l": "I do forget.--"
   },
   {
    "l": "Do not muse at me, my most worthy friends."
   },
   {
    "l": "I have a strange infirmity, which is nothing"
   },
   {
    "l": "To those that know me. Come, love and health to all;"
   },
   {
    "l": "Then I'll sit down.--Give me some wine, fill full.--"
   },
   {
    "l": "I drink to the general joy o' th' whole table,"
   },
   {
    "l": "And to our dear friend Banquo, whom we miss:"
   },
   {
    "l": "Would he were here."
   },
   {
    "s": "Ghost rises again."
   },
   {
    "l": "To all, and him, we thirst,"
   },
   {
    "l": "And all to all."
   }
  ],
  "word": "I"
 },
 {
  "act": "3",
  "sc": "4",
  "n": 95,
  "who": "Lords",
  "cue": [
   "Our duties, and the pledge."
  ],
  "speech": [
   {
    "l": "Avaunt! and quit my sight! let the earth hide thee!"
   },
   {
    "l": "Thy bones are marrowless, thy blood is cold;"
   },
   {
    "l": "Thou hast no speculation in those eyes"
   },
   {
    "l": "Which thou dost glare with!"
   }
  ],
  "word": "Avaunt"
 },
 {
  "act": "3",
  "sc": "4",
  "n": 100,
  "who": "Lady Macbeth",
  "cue": [
   "Think of this, good peers,",
   "But as a thing of custom: 'tis no other,",
   "Only it spoils the pleasure of the time."
  ],
  "speech": [
   {
    "l": "What man dare, I dare:"
   },
   {
    "l": "Approach thou like the rugged Russian bear,"
   },
   {
    "l": "The arm'd rhinoceros, or th' Hyrcan tiger;"
   },
   {
    "l": "Take any shape but that, and my firm nerves"
   },
   {
    "l": "Shall never tremble: or be alive again,"
   },
   {
    "l": "And dare me to the desert with thy sword;"
   },
   {
    "l": "If trembling I inhabit then, protest me"
   },
   {
    "l": "The baby of a girl. Hence, horrible shadow!"
   },
   {
    "l": "Unreal mock'ry, hence!"
   },
   {
    "s": "Ghost disappears."
   },
   {
    "l": "Why, so;--being gone,"
   },
   {
    "l": "I am a man again.--Pray you, sit still."
   }
  ],
  "word": "What"
 },
 {
  "act": "3",
  "sc": "4",
  "n": 110,
  "who": "Lady Macbeth",
  "cue": [
   "You have displaced the mirth, broke the good meeting",
   "With most admir'd disorder."
  ],
  "speech": [
   {
    "l": "Can such things be,"
   },
   {
    "l": "And overcome us like a summer's cloud,"
   },
   {
    "l": "Without our special wonder? You make me strange"
   },
   {
    "l": "Even to the disposition that I owe,"
   },
   {
    "l": "When now I think you can behold such sights,"
   },
   {
    "l": "And keep the natural ruby of your cheeks,"
   },
   {
    "l": "When mine are blanch'd with fear."
   }
  ],
  "word": "Can"
 },
 {
  "act": "3",
  "sc": "4",
  "n": 122,
  "who": "Lady Macbeth",
  "cue": [
   "A kind good night to all!"
  ],
  "speech": [
   {
    "l": "It will have blood, they say, blood will have blood."
   },
   {
    "l": "Stones have been known to move, and trees to speak;"
   },
   {
    "l": "Augurs, and understood relations, have"
   },
   {
    "l": "By magot-pies, and choughs, and rooks, brought forth"
   },
   {
    "l": "The secret'st man of blood.--What is the night?"
   }
  ],
  "word": "It"
 },
 {
  "act": "3",
  "sc": "4",
  "n": 127,
  "who": "Lady Macbeth",
  "cue": [
   "Almost at odds with morning, which is which."
  ],
  "speech": [
   {
    "l": "How say'st thou, that Macduff denies his person"
   },
   {
    "l": "At our great bidding?"
   }
  ],
  "word": "How"
 },
 {
  "act": "3",
  "sc": "4",
  "n": 129,
  "who": "Lady Macbeth",
  "cue": [
   "Did you send to him, sir?"
  ],
  "speech": [
   {
    "l": "I hear it by the way; but I will send."
   },
   {
    "l": "There's not a one of them but in his house"
   },
   {
    "l": "I keep a servant fee'd. I will tomorrow"
   },
   {
    "l": "(And betimes I will) to the Weird Sisters:"
   },
   {
    "l": "More shall they speak; for now I am bent to know,"
   },
   {
    "l": "By the worst means, the worst. For mine own good,"
   },
   {
    "l": "All causes shall give way: I am in blood"
   },
   {
    "l": "Stepp'd in so far that, should I wade no more,"
   },
   {
    "l": "Returning were as tedious as go o'er."
   },
   {
    "l": "Strange things I have in head, that will to hand,"
   },
   {
    "l": "Which must be acted ere they may be scann'd."
   }
  ],
  "word": "I"
 },
 {
  "act": "3",
  "sc": "4",
  "n": 141,
  "who": "Lady Macbeth",
  "cue": [
   "You lack the season of all natures, sleep."
  ],
  "speech": [
   {
    "l": "Come, we'll to sleep. My strange and self-abuse"
   },
   {
    "l": "Is the initiate fear that wants hard use."
   },
   {
    "l": "We are yet but young in deed."
   }
  ],
  "word": "Come"
 },
 {
  "act": "4",
  "sc": "1",
  "n": 47,
  "who": "Second Witch",
  "cue": [
   "Something wicked this way comes.",
   "Open, locks,",
   "Whoever knocks!"
  ],
  "speech": [
   {
    "l": "How now, you secret, black, and midnight hags!"
   },
   {
    "l": "What is't you do?"
   }
  ],
  "word": "How"
 },
 {
  "act": "4",
  "sc": "1",
  "n": 50,
  "who": "All",
  "cue": [
   "A deed without a name."
  ],
  "speech": [
   {
    "l": "I conjure you, by that which you profess,"
   },
   {
    "l": "(Howe'er you come to know it) answer me:"
   },
   {
    "l": "Though you untie the winds, and let them fight"
   },
   {
    "l": "Against the churches; though the yesty waves"
   },
   {
    "l": "Confound and swallow navigation up;"
   },
   {
    "l": "Though bladed corn be lodg'd, and trees blown down;"
   },
   {
    "l": "Though castles topple on their warders' heads;"
   },
   {
    "l": "Though palaces and pyramids do slope"
   },
   {
    "l": "Their heads to their foundations; though the treasure"
   },
   {
    "l": "Of nature's germens tumble all together,"
   },
   {
    "l": "Even till destruction sicken, answer me"
   },
   {
    "l": "To what I ask you."
   }
  ],
  "word": "I"
 },
 {
  "act": "4",
  "sc": "1",
  "n": 64,
  "who": "First Witch",
  "cue": [
   "Say, if thou'dst rather hear it from our mouths,",
   "Or from our masters?"
  ],
  "speech": [
   {
    "l": "Call 'em, let me see 'em."
   }
  ],
  "word": "Call"
 },
 {
  "act": "4",
  "sc": "1",
  "n": 69,
  "who": "All",
  "cue": [
   "Come, high or low;",
   "Thyself and office deftly show!"
  ],
  "speech": [
   {
    "l": "Tell me, thou unknown power,--"
   }
  ],
  "word": "Tell"
 },
 {
  "act": "4",
  "sc": "1",
  "n": 73,
  "who": "Apparition",
  "cue": [
   "Macbeth! Macbeth! Macbeth! Beware Macduff;",
   "Beware the Thane of Fife.--Dismiss me.--Enough."
  ],
  "speech": [
   {
    "l": "Whate'er thou art, for thy good caution, thanks;"
   },
   {
    "l": "Thou hast harp'd my fear aright.--But one word more."
   }
  ],
  "word": "Whate'er"
 },
 {
  "act": "4",
  "sc": "1",
  "n": 78,
  "who": "Apparition",
  "cue": [
   "Macbeth! Macbeth! Macbeth!"
  ],
  "speech": [
   {
    "l": "Had I three ears, I'd hear thee."
   }
  ],
  "word": "Had"
 },
 {
  "act": "4",
  "sc": "1",
  "n": 82,
  "who": "Apparition",
  "cue": [
   "Be bloody, bold, and resolute. Laugh to scorn",
   "The power of man, for none of woman born",
   "Shall harm Macbeth."
  ],
  "speech": [
   {
    "l": "Then live, Macduff: what need I fear of thee?"
   },
   {
    "l": "But yet I'll make assurance double sure,"
   },
   {
    "l": "And take a bond of fate. Thou shalt not live;"
   },
   {
    "l": "That I may tell pale-hearted fear it lies,"
   },
   {
    "l": "And sleep in spite of thunder."
   },
   {
    "s": "Thunder. An Apparition of a Child crowned, with a tree in his hand, rises."
   },
   {
    "l": "What is this,"
   },
   {
    "l": "That rises like the issue of a king,"
   },
   {
    "l": "And wears upon his baby brow the round"
   },
   {
    "l": "And top of sovereignty?"
   }
  ],
  "word": "Then"
 },
 {
  "act": "4",
  "sc": "1",
  "n": 95,
  "who": "Apparition",
  "cue": [
   "Macbeth shall never vanquish'd be, until",
   "Great Birnam wood to high Dunsinane hill",
   "Shall come against him."
  ],
  "speech": [
   {
    "l": "That will never be:"
   },
   {
    "l": "Who can impress the forest; bid the tree"
   },
   {
    "l": "Unfix his earth-bound root? Sweet bodements, good!"
   },
   {
    "l": "Rebellious head, rise never till the wood"
   },
   {
    "l": "Of Birnam rise, and our high-plac'd Macbeth"
   },
   {
    "l": "Shall live the lease of nature, pay his breath"
   },
   {
    "l": "To time and mortal custom.--Yet my heart"
   },
   {
    "l": "Throbs to know one thing: tell me, if your art"
   },
   {
    "l": "Can tell so much, shall Banquo's issue ever"
   },
   {
    "l": "Reign in this kingdom?"
   }
  ],
  "word": "That"
 },
 {
  "act": "4",
  "sc": "1",
  "n": 105,
  "who": "All",
  "cue": [
   "Seek to know no more."
  ],
  "speech": [
   {
    "l": "I will be satisfied: deny me this,"
   },
   {
    "l": "And an eternal curse fall on you! Let me know."
   },
   {
    "l": "Why sinks that cauldron? and what noise is this?"
   }
  ],
  "word": "I"
 },
 {
  "act": "4",
  "sc": "1",
  "n": 112,
  "who": "All",
  "cue": [
   "Show his eyes, and grieve his heart;",
   "Come like shadows, so depart!"
  ],
  "speech": [
   {
    "l": "Thou are too like the spirit of Banquo. Down!"
   },
   {
    "l": "Thy crown does sear mine eyeballs:--and thy hair,"
   },
   {
    "l": "Thou other gold-bound brow, is like the first."
   },
   {
    "l": "A third is like the former.--Filthy hags!"
   },
   {
    "l": "Why do you show me this?--A fourth!--Start, eyes!"
   },
   {
    "l": "What, will the line stretch out to th' crack of doom?"
   },
   {
    "l": "Another yet!--A seventh!--I'll see no more:--"
   },
   {
    "l": "And yet the eighth appears, who bears a glass"
   },
   {
    "l": "Which shows me many more; and some I see"
   },
   {
    "l": "That twofold balls and treble sceptres carry."
   },
   {
    "l": "Horrible sight!--Now I see 'tis true;"
   },
   {
    "l": "For the blood-bolter'd Banquo smiles upon me,"
   },
   {
    "l": "And points at them for his.--What! is this so?"
   }
  ],
  "word": "Thou"
 },
 {
  "act": "4",
  "sc": "1",
  "n": 132,
  "who": "First Witch",
  "cue": [
   "While you perform your antic round;",
   "That this great king may kindly say,",
   "Our duties did his welcome pay."
  ],
  "speech": [
   {
    "l": "Where are they? Gone?--Let this pernicious hour"
   },
   {
    "l": "Stand aye accursed in the calendar!--"
   },
   {
    "l": "Come in, without there!"
   }
  ],
  "word": "Where"
 },
 {
  "act": "4",
  "sc": "1",
  "n": 135,
  "who": "Lennox",
  "cue": [
   "What's your Grace's will?"
  ],
  "speech": [
   {
    "l": "Saw you the Weird Sisters?"
   }
  ],
  "word": "Saw"
 },
 {
  "act": "4",
  "sc": "1",
  "n": 137,
  "who": "Lennox",
  "cue": [
   "No, my lord."
  ],
  "speech": [
   {
    "l": "Came they not by you?"
   }
  ],
  "word": "Came"
 },
 {
  "act": "4",
  "sc": "1",
  "n": 138,
  "who": "Lennox",
  "cue": [
   "No, indeed, my lord."
  ],
  "speech": [
   {
    "l": "Infected be the air whereon they ride;"
   },
   {
    "l": "And damn'd all those that trust them!--I did hear"
   },
   {
    "l": "The galloping of horse: who was't came by?"
   }
  ],
  "word": "Infected"
 },
 {
  "act": "4",
  "sc": "1",
  "n": 143,
  "who": "Lennox",
  "cue": [
   "'Tis two or three, my lord, that bring you word",
   "Macduff is fled to England."
  ],
  "speech": [
   {
    "l": "Fled to England!"
   }
  ],
  "word": "Fled"
 },
 {
  "act": "4",
  "sc": "1",
  "n": 145,
  "who": "Lennox",
  "cue": [
   "Ay, my good lord."
  ],
  "speech": [
   {
    "l": "Time, thou anticipat'st my dread exploits:"
   },
   {
    "l": "The flighty purpose never is o'ertook"
   },
   {
    "l": "Unless the deed go with it. From this moment"
   },
   {
    "l": "The very firstlings of my heart shall be"
   },
   {
    "l": "The firstlings of my hand. And even now,"
   },
   {
    "l": "To crown my thoughts with acts, be it thought and done:"
   },
   {
    "l": "The castle of Macduff I will surprise;"
   },
   {
    "l": "Seize upon Fife; give to th' edge o' th' sword"
   },
   {
    "l": "His wife, his babes, and all unfortunate souls"
   },
   {
    "l": "That trace him in his line. No boasting like a fool;"
   },
   {
    "l": "This deed I'll do before this purpose cool:"
   },
   {
    "l": "But no more sights!--Where are these gentlemen?"
   },
   {
    "l": "Come, bring me where they are."
   }
  ],
  "word": "Time"
 },
 {
  "act": "5",
  "sc": "3",
  "n": 13,
  "who": "Servant",
  "cue": [
   "There is ten thousand--"
  ],
  "speech": [
   {
    "l": "Geese, villain?"
   }
  ],
  "word": "Geese"
 },
 {
  "act": "5",
  "sc": "3",
  "n": 15,
  "who": "Servant",
  "cue": [
   "Soldiers, sir."
  ],
  "speech": [
   {
    "l": "Go prick thy face and over-red thy fear,"
   },
   {
    "l": "Thou lily-liver'd boy. What soldiers, patch?"
   },
   {
    "l": "Death of thy soul! those linen cheeks of thine"
   },
   {
    "l": "Are counsellors to fear. What soldiers, whey-face?"
   }
  ],
  "word": "Go"
 },
 {
  "act": "5",
  "sc": "3",
  "n": 18,
  "who": "Servant",
  "cue": [
   "The English force, so please you."
  ],
  "speech": [
   {
    "l": "Take thy face hence."
   },
   {
    "s": "Exit Servant."
   },
   {
    "l": "Seyton!--I am sick at heart,"
   },
   {
    "l": "When I behold--Seyton, I say!--This push"
   },
   {
    "l": "Will cheer me ever or disseat me now."
   },
   {
    "l": "I have liv'd long enough: my way of life"
   },
   {
    "l": "Is fall'n into the sere, the yellow leaf;"
   },
   {
    "l": "And that which should accompany old age,"
   },
   {
    "l": "As honour, love, obedience, troops of friends,"
   },
   {
    "l": "I must not look to have; but, in their stead,"
   },
   {
    "l": "Curses, not loud but deep, mouth-honour, breath,"
   },
   {
    "l": "Which the poor heart would fain deny, and dare not."
   },
   {
    "l": "Seyton!--"
   }
  ],
  "word": "Take"
 },
 {
  "act": "5",
  "sc": "3",
  "n": 30,
  "who": "Seyton",
  "cue": [
   "What's your gracious pleasure?"
  ],
  "speech": [
   {
    "l": "What news more?"
   }
  ],
  "word": "What"
 },
 {
  "act": "5",
  "sc": "3",
  "n": 32,
  "who": "Seyton",
  "cue": [
   "All is confirm'd, my lord, which was reported."
  ],
  "speech": [
   {
    "l": "I'll fight till from my bones my flesh be hack'd."
   },
   {
    "l": "Give me my armour."
   }
  ],
  "word": "I'll"
 },
 {
  "act": "5",
  "sc": "3",
  "n": 34,
  "who": "Seyton",
  "cue": [
   "'Tis not needed yet."
  ],
  "speech": [
   {
    "l": "I'll put it on."
   },
   {
    "l": "Send out more horses, skirr the country round;"
   },
   {
    "l": "Hang those that talk of fear. Give me mine armour.--"
   },
   {
    "l": "How does your patient, doctor?"
   }
  ],
  "word": "I'll"
 },
 {
  "act": "5",
  "sc": "3",
  "n": 39,
  "who": "Doctor",
  "cue": [
   "Not so sick, my lord,",
   "As she is troubled with thick-coming fancies,",
   "That keep her from her rest."
  ],
  "speech": [
   {
    "l": "Cure her of that:"
   },
   {
    "l": "Canst thou not minister to a mind diseas'd,"
   },
   {
    "l": "Pluck from the memory a rooted sorrow,"
   },
   {
    "l": "Raze out the written troubles of the brain,"
   },
   {
    "l": "And with some sweet oblivious antidote"
   },
   {
    "l": "Cleanse the stuff'd bosom of that perilous stuff"
   },
   {
    "l": "Which weighs upon the heart?"
   }
  ],
  "word": "Cure"
 },
 {
  "act": "5",
  "sc": "3",
  "n": 48,
  "who": "Doctor",
  "cue": [
   "Therein the patient",
   "Must minister to himself."
  ],
  "speech": [
   {
    "l": "Throw physic to the dogs, I'll none of it."
   },
   {
    "l": "Come, put mine armour on; give me my staff:"
   },
   {
    "l": "Seyton, send out.--Doctor, the Thanes fly from me.--"
   },
   {
    "l": "Come, sir, despatch.--If thou couldst, doctor, cast"
   },
   {
    "l": "The water of my land, find her disease,"
   },
   {
    "l": "And purge it to a sound and pristine health,"
   },
   {
    "l": "I would applaud thee to the very echo,"
   },
   {
    "l": "That should applaud again.--Pull't off, I say.--"
   },
   {
    "l": "What rhubarb, senna, or what purgative drug,"
   },
   {
    "l": "Would scour these English hence? Hear'st thou of them?"
   }
  ],
  "word": "Throw"
 },
 {
  "act": "5",
  "sc": "3",
  "n": 58,
  "who": "Doctor",
  "cue": [
   "Ay, my good lord. Your royal preparation",
   "Makes us hear something."
  ],
  "speech": [
   {
    "l": "Bring it after me.--"
   },
   {
    "l": "I will not be afraid of death and bane,"
   },
   {
    "l": "Till Birnam forest come to Dunsinane."
   }
  ],
  "word": "Bring"
 },
 {
  "act": "5",
  "sc": "5",
  "n": 9,
  "who": "Seyton",
  "cue": [
   "It is the cry of women, my good lord."
  ],
  "speech": [
   {
    "l": "I have almost forgot the taste of fears."
   },
   {
    "l": "The time has been, my senses would have cool'd"
   },
   {
    "l": "To hear a night-shriek; and my fell of hair"
   },
   {
    "l": "Would at a dismal treatise rouse and stir"
   },
   {
    "l": "As life were in't. I have supp'd full with horrors;"
   },
   {
    "l": "Direness, familiar to my slaughterous thoughts,"
   },
   {
    "l": "Cannot once start me."
   },
   {
    "s": "Enter Seyton."
   },
   {
    "l": "Wherefore was that cry?"
   }
  ],
  "word": "I"
 },
 {
  "act": "5",
  "sc": "5",
  "n": 17,
  "who": "Seyton",
  "cue": [
   "The Queen, my lord, is dead."
  ],
  "speech": [
   {
    "l": "She should have died hereafter."
   },
   {
    "l": "There would have been a time for such a word."
   },
   {
    "l": "Tomorrow, and tomorrow, and tomorrow,"
   },
   {
    "l": "Creeps in this petty pace from day to day,"
   },
   {
    "l": "To the last syllable of recorded time;"
   },
   {
    "l": "And all our yesterdays have lighted fools"
   },
   {
    "l": "The way to dusty death. Out, out, brief candle!"
   },
   {
    "l": "Life's but a walking shadow; a poor player,"
   },
   {
    "l": "That struts and frets his hour upon the stage,"
   },
   {
    "l": "And then is heard no more: it is a tale"
   },
   {
    "l": "Told by an idiot, full of sound and fury,"
   },
   {
    "l": "Signifying nothing."
   },
   {
    "s": "Enter a Messenger."
   },
   {
    "l": "Thou com'st to use thy tongue; thy story quickly."
   }
  ],
  "word": "She"
 },
 {
  "act": "5",
  "sc": "5",
  "n": 32,
  "who": "Messenger",
  "cue": [
   "Gracious my lord,",
   "I should report that which I say I saw,",
   "But know not how to do't."
  ],
  "speech": [
   {
    "l": "Well, say, sir."
   }
  ],
  "word": "Well"
 },
 {
  "act": "5",
  "sc": "5",
  "n": 36,
  "who": "Messenger",
  "cue": [
   "As I did stand my watch upon the hill,",
   "I look'd toward Birnam, and anon, methought,",
   "The wood began to move."
  ],
  "speech": [
   {
    "l": "Liar, and slave!"
   }
  ],
  "word": "Liar"
 },
 {
  "act": "5",
  "sc": "5",
  "n": 38,
  "who": "Messenger",
  "cue": [
   "I say, a moving grove."
  ],
  "speech": [
   {
    "l": "If thou speak'st false,"
   },
   {
    "l": "Upon the next tree shalt thou hang alive,"
   },
   {
    "l": "Till famine cling thee: if thy speech be sooth,"
   },
   {
    "l": "I care not if thou dost for me as much.--"
   },
   {
    "l": "I pull in resolution; and begin"
   },
   {
    "l": "To doubt th' equivocation of the fiend,"
   },
   {
    "l": "That lies like truth. \"Fear not, till Birnam wood"
   },
   {
    "l": "Do come to Dunsinane;\" and now a wood"
   },
   {
    "l": "Comes toward Dunsinane.--Arm, arm, and out!--"
   },
   {
    "l": "If this which he avouches does appear,"
   },
   {
    "l": "There is nor flying hence nor tarrying here."
   },
   {
    "l": "I 'gin to be aweary of the sun,"
   },
   {
    "l": "And wish th' estate o' th' world were now undone.--"
   },
   {
    "l": "Ring the alarum bell!--Blow, wind! come, wrack!"
   },
   {
    "l": "At least we'll die with harness on our back."
   }
  ],
  "word": "If"
 },
 {
  "act": "5",
  "sc": "7",
  "n": 5,
  "who": "Young Siward",
  "cue": [
   "What is thy name?"
  ],
  "speech": [
   {
    "l": "Thou'lt be afraid to hear it."
   }
  ],
  "word": "Thou'lt"
 },
 {
  "act": "5",
  "sc": "7",
  "n": 7,
  "who": "Young Siward",
  "cue": [
   "No; though thou call'st thyself a hotter name",
   "Than any is in hell."
  ],
  "speech": [
   {
    "l": "My name's Macbeth."
   }
  ],
  "word": "My"
 },
 {
  "act": "5",
  "sc": "7",
  "n": 9,
  "who": "Young Siward",
  "cue": [
   "The devil himself could not pronounce a title",
   "More hateful to mine ear."
  ],
  "speech": [
   {
    "l": "No, nor more fearful."
   }
  ],
  "word": "No"
 },
 {
  "act": "5",
  "sc": "7",
  "n": 12,
  "who": "Young Siward",
  "cue": [
   "Thou liest, abhorred tyrant. With my sword",
   "I'll prove the lie thou speak'st."
  ],
  "speech": [
   {
    "l": "Thou wast born of woman."
   },
   {
    "l": "But swords I smile at, weapons laugh to scorn,"
   },
   {
    "l": "Brandish'd by man that's of a woman born."
   }
  ],
  "word": "Thou"
 },
 {
  "act": "5",
  "sc": "8",
  "n": 4,
  "who": "Macduff",
  "cue": [
   "Turn, hell-hound, turn!"
  ],
  "speech": [
   {
    "l": "Of all men else I have avoided thee:"
   },
   {
    "l": "But get thee back; my soul is too much charg'd"
   },
   {
    "l": "With blood of thine already."
   }
  ],
  "word": "Of"
 },
 {
  "act": "5",
  "sc": "8",
  "n": 8,
  "who": "Macduff",
  "cue": [
   "I have no words;",
   "My voice is in my sword: thou bloodier villain",
   "Than terms can give thee out!"
  ],
  "speech": [
   {
    "l": "Thou losest labour:"
   },
   {
    "l": "As easy mayst thou the intrenchant air"
   },
   {
    "l": "With thy keen sword impress, as make me bleed:"
   },
   {
    "l": "Let fall thy blade on vulnerable crests;"
   },
   {
    "l": "I bear a charmed life, which must not yield"
   },
   {
    "l": "To one of woman born."
   }
  ],
  "word": "Thou"
 },
 {
  "act": "5",
  "sc": "8",
  "n": 17,
  "who": "Macduff",
  "cue": [
   "And let the angel whom thou still hast serv'd",
   "Tell thee, Macduff was from his mother's womb",
   "Untimely ripp'd."
  ],
  "speech": [
   {
    "l": "Accursed be that tongue that tells me so,"
   },
   {
    "l": "For it hath cow'd my better part of man!"
   },
   {
    "l": "And be these juggling fiends no more believ'd,"
   },
   {
    "l": "That palter with us in a double sense;"
   },
   {
    "l": "That keep the word of promise to our ear,"
   },
   {
    "l": "And break it to our hope!--I'll not fight with thee."
   }
  ],
  "word": "Accursed"
 },
 {
  "act": "5",
  "sc": "8",
  "n": 28,
  "who": "Macduff",
  "cue": [
   "We'll have thee, as our rarer monsters are,",
   "Painted upon a pole, and underwrit,",
   "\"Here may you see the tyrant.\""
  ],
  "speech": [
   {
    "l": "I will not yield,"
   },
   {
    "l": "To kiss the ground before young Malcolm's feet,"
   },
   {
    "l": "And to be baited with the rabble's curse."
   },
   {
    "l": "Though Birnam wood be come to Dunsinane,"
   },
   {
    "l": "And thou oppos'd, being of no woman born,"
   },
   {
    "l": "Yet I will try the last. Before my body"
   },
   {
    "l": "I throw my warlike shield: lay on, Macduff;"
   },
   {
    "l": "And damn'd be him that first cries, \"Hold, enough!\""
   }
  ],
  "word": "I"
 }
];
