-- Generated by tools/mirror-site.py. Replaceable photographs
-- on the public pages. Safe to re-run.

insert into public.site_images (page, img_key, original_src, alt, bytes)
values ('index.html', '1', 'site/group-0a7bcd4c.jpg', '', 258861)
on conflict (page, img_key) do update set original_src = excluded.original_src,
  alt = excluded.alt, bytes = excluded.bytes;
