-- Generated by tools/mirror-site.py. Every editable text block on the
-- public pages, with the wording it was imported with.
--
-- Safe to re-run: existing rows keep their `text` override and only the
-- original is refreshed, so re-importing the site does not silently throw
-- away somebody's edits.

insert into public.site_content (page, block_key, original, sort_order, tag) values
  ('index.html', '1', 'Koinonia Homeschool Group', 1, 'h1')
on conflict (page, block_key) do update set original = excluded.original,
  sort_order = excluded.sort_order, tag = excluded.tag;
insert into public.site_content (page, block_key, original, sort_order, tag) values
  ('index.html', '2', 'Providing elective and enrichment opportunities for Christian homeschoolers in the Phoenix area.', 2, 'p')
on conflict (page, block_key) do update set original = excluded.original,
  sort_order = excluded.sort_order, tag = excluded.tag;
insert into public.site_content (page, block_key, original, sort_order, tag) values
  ('index.html', '3', 'What is Koinonia?', 3, 'h2')
on conflict (page, block_key) do update set original = excluded.original,
  sort_order = excluded.sort_order, tag = excluded.tag;
insert into public.site_content (page, block_key, original, sort_order, tag) values
  ('index.html', '4', 'Koinonia is a transliterated form of the Greek word κοινωνία, which refers to concepts such as fellowship, joint participation, and the share which one has in anything.', 4, 'p')
on conflict (page, block_key) do update set original = excluded.original,
  sort_order = excluded.sort_order, tag = excluded.tag;
insert into public.site_content (page, block_key, original, sort_order, tag) values
  ('index.html', '5', 'We started as three homeschool moms in Phoenix, Arizona with a vision for a Christ-centered homeschool community for our kids and ourselves. We each come from different backgrounds and paths in life, but we’ve been brought together by our love for Jesus Christ and our passion for our families and our kids’ education. We believe that a big part of their education is teaching them to participate in the body of Christ (1 Corinthians 12: 12-31) and the community in which we live (Jeremiah 29:7). We also want to make the most of our different gifts and talents, and recognize our own need as moms to have community and be encouraged by one another.', 5, 'p')
on conflict (page, block_key) do update set original = excluded.original,
  sort_order = excluded.sort_order, tag = excluded.tag;
insert into public.site_content (page, block_key, original, sort_order, tag) values
  ('index.html', '6', 'Joining Koinonia HomeSchool group has been such a blessing for our family. We have met many new friends along the way.  Our children enjoy the crafts and activities and of course the social time with others each Thursday!', 6, 'p')
on conflict (page, block_key) do update set original = excluded.original,
  sort_order = excluded.sort_order, tag = excluded.tag;
insert into public.site_content (page, block_key, original, sort_order, tag) values
  ('index.html', '7', 'Latest from the Blog', 7, 'h4')
on conflict (page, block_key) do update set original = excluded.original,
  sort_order = excluded.sort_order, tag = excluded.tag;
insert into public.site_content (page, block_key, original, sort_order, tag) values
  ('index.html', '8', '[Homeschooled in Africa](https://koinoniaphx.com/2021/07/07/homeschooled-in-africa/)', 8, 'h2')
on conflict (page, block_key) do update set original = excluded.original,
  sort_order = excluded.sort_order, tag = excluded.tag;
insert into public.site_content (page, block_key, original, sort_order, tag) values
  ('index.html', '9', 'As we sat there in the principal’s office on our first day at Rosslyn Academy in 1994, Mr. Richardson looked slowly around at all of us. He then looked at my mother, nervously clutching her manila folder of handwritten homeschool records, and said, “I don’t like homeschoolers”. Shocking I know! My mother gulped and started…', 9, 'p')
on conflict (page, block_key) do update set original = excluded.original,
  sort_order = excluded.sort_order, tag = excluded.tag;
insert into public.site_content (page, block_key, original, sort_order, tag) values
  ('about-koinonia-faq/index.html', '1', 'Overview', 1, 'h4')
on conflict (page, block_key) do update set original = excluded.original,
  sort_order = excluded.sort_order, tag = excluded.tag;
insert into public.site_content (page, block_key, original, sort_order, tag) values
  ('about-koinonia-faq/index.html', '2', 'Koinonia Homeschool Group exists for two main reasons: to provide community, enrichment and elective opportunities to homeschoolers in the Phoenix area, and to provide community and support to their moms, deep in the trenches of homeschooling.', 2, 'p')
on conflict (page, block_key) do update set original = excluded.original,
  sort_order = excluded.sort_order, tag = excluded.tag;
insert into public.site_content (page, block_key, original, sort_order, tag) values
  ('about-koinonia-faq/index.html', '3', 'What do we do?', 3, 'h4')
on conflict (page, block_key) do update set original = excluded.original,
  sort_order = excluded.sort_order, tag = excluded.tag;
insert into public.site_content (page, block_key, original, sort_order, tag) values
  ('about-koinonia-faq/index.html', '4', 'Koinonia meets weekly on Thursday afternoons for parent-led classes. Families are encouraged to stay for the entirety of the afternoon. We have a brief opening meeting, then break out into various classes for three 50 minute sessions, leaving 20 minutes at the end of our day to use as needed for clean up.', 4, 'p')
on conflict (page, block_key) do update set original = excluded.original,
  sort_order = excluded.sort_order, tag = excluded.tag;
insert into public.site_content (page, block_key, original, sort_order, tag) values
  ('about-koinonia-faq/index.html', '5', 'We strive to have multiple options in every session for every age group.', 5, 'p')
on conflict (page, block_key) do update set original = excluded.original,
  sort_order = excluded.sort_order, tag = excluded.tag;
insert into public.site_content (page, block_key, original, sort_order, tag) values
  ('about-koinonia-faq/index.html', '6', 'Past classes have included:', 6, 'p')
on conflict (page, block_key) do update set original = excluded.original,
  sort_order = excluded.sort_order, tag = excluded.tag;
insert into public.site_content (page, block_key, original, sort_order, tag) values
  ('about-koinonia-faq/index.html', '7', 'Choir', 7, 'li')
on conflict (page, block_key) do update set original = excluded.original,
  sort_order = excluded.sort_order, tag = excluded.tag;
insert into public.site_content (page, block_key, original, sort_order, tag) values
  ('about-koinonia-faq/index.html', '8', 'Acting', 8, 'li')
on conflict (page, block_key) do update set original = excluded.original,
  sort_order = excluded.sort_order, tag = excluded.tag;
insert into public.site_content (page, block_key, original, sort_order, tag) values
  ('about-koinonia-faq/index.html', '9', 'Art', 9, 'li')
on conflict (page, block_key) do update set original = excluded.original,
  sort_order = excluded.sort_order, tag = excluded.tag;
insert into public.site_content (page, block_key, original, sort_order, tag) values
  ('about-koinonia-faq/index.html', '10', 'Public Speaking', 10, 'li')
on conflict (page, block_key) do update set original = excluded.original,
  sort_order = excluded.sort_order, tag = excluded.tag;
insert into public.site_content (page, block_key, original, sort_order, tag) values
  ('about-koinonia-faq/index.html', '11', 'Sewing', 11, 'li')
on conflict (page, block_key) do update set original = excluded.original,
  sort_order = excluded.sort_order, tag = excluded.tag;
insert into public.site_content (page, block_key, original, sort_order, tag) values
  ('about-koinonia-faq/index.html', '12', 'Chess', 12, 'li')
on conflict (page, block_key) do update set original = excluded.original,
  sort_order = excluded.sort_order, tag = excluded.tag;
insert into public.site_content (page, block_key, original, sort_order, tag) values
  ('about-koinonia-faq/index.html', '13', 'Nature', 13, 'li')
on conflict (page, block_key) do update set original = excluded.original,
  sort_order = excluded.sort_order, tag = excluded.tag;
insert into public.site_content (page, block_key, original, sort_order, tag) values
  ('about-koinonia-faq/index.html', '14', 'World Missions', 14, 'li')
on conflict (page, block_key) do update set original = excluded.original,
  sort_order = excluded.sort_order, tag = excluded.tag;
insert into public.site_content (page, block_key, original, sort_order, tag) values
  ('about-koinonia-faq/index.html', '15', 'Book Clubs', 15, 'li')
on conflict (page, block_key) do update set original = excluded.original,
  sort_order = excluded.sort_order, tag = excluded.tag;
insert into public.site_content (page, block_key, original, sort_order, tag) values
  ('about-koinonia-faq/index.html', '16', 'ASL', 16, 'li')
on conflict (page, block_key) do update set original = excluded.original,
  sort_order = excluded.sort_order, tag = excluded.tag;
insert into public.site_content (page, block_key, original, sort_order, tag) values
  ('about-koinonia-faq/index.html', '17', 'Cooking', 17, 'li')
on conflict (page, block_key) do update set original = excluded.original,
  sort_order = excluded.sort_order, tag = excluded.tag;
insert into public.site_content (page, block_key, original, sort_order, tag) values
  ('about-koinonia-faq/index.html', '18', 'PE', 18, 'li')
on conflict (page, block_key) do update set original = excluded.original,
  sort_order = excluded.sort_order, tag = excluded.tag;
insert into public.site_content (page, block_key, original, sort_order, tag) values
  ('about-koinonia-faq/index.html', '19', 'Running', 19, 'li')
on conflict (page, block_key) do update set original = excluded.original,
  sort_order = excluded.sort_order, tag = excluded.tag;
insert into public.site_content (page, block_key, original, sort_order, tag) values
  ('about-koinonia-faq/index.html', '20', 'STEM/STEAM', 20, 'li')
on conflict (page, block_key) do update set original = excluded.original,
  sort_order = excluded.sort_order, tag = excluded.tag;
insert into public.site_content (page, block_key, original, sort_order, tag) values
  ('about-koinonia-faq/index.html', '21', 'Christian worldview', 21, 'li')
on conflict (page, block_key) do update set original = excluded.original,
  sort_order = excluded.sort_order, tag = excluded.tag;
insert into public.site_content (page, block_key, original, sort_order, tag) values
  ('about-koinonia-faq/index.html', '22', 'The classes offered are completely dependent on the gifts and passions of the members of the group, and will vary from semester to semester.', 22, 'p')
on conflict (page, block_key) do update set original = excluded.original,
  sort_order = excluded.sort_order, tag = excluded.tag;
insert into public.site_content (page, block_key, original, sort_order, tag) values
  ('about-koinonia-faq/index.html', '23', 'Who should join Koinonia?', 23, 'h4')
on conflict (page, block_key) do update set original = excluded.original,
  sort_order = excluded.sort_order, tag = excluded.tag;
insert into public.site_content (page, block_key, original, sort_order, tag) values
  ('about-koinonia-faq/index.html', '24', 'Koinonia membership is open to Christian families who homeschool their children, and who’s oldest child is at least five years old by our semester’s start date. Preschool classes and nursery will be available to younger siblings. Anyone interested in joining must [apply for membership](../apply/) through the website and agree to Koinonia’s [statement of faith and code of conduct.](../our-beliefs/)', 24, 'p')
on conflict (page, block_key) do update set original = excluded.original,
  sort_order = excluded.sort_order, tag = excluded.tag;
insert into public.site_content (page, block_key, original, sort_order, tag) values
  ('about-koinonia-faq/index.html', '25', 'What is expected of parents?', 25, 'h4')
on conflict (page, block_key) do update set original = excluded.original,
  sort_order = excluded.sort_order, tag = excluded.tag;
insert into public.site_content (page, block_key, original, sort_order, tag) values
  ('about-koinonia-faq/index.html', '26', 'At least one parent from every family must be on campus during co-op days, and participate in either teaching or helping during at least 2 out of the 3 sessions. Parents are required to help clean up at the end of every weekly meeting. All parents are expected to review the statement of faith and code of conduct with their children.', 26, 'p')
on conflict (page, block_key) do update set original = excluded.original,
  sort_order = excluded.sort_order, tag = excluded.tag;
insert into public.site_content (page, block_key, original, sort_order, tag) values
  ('about-koinonia-faq/index.html', '27', 'What is expected of students?', 27, 'h4')
on conflict (page, block_key) do update set original = excluded.original,
  sort_order = excluded.sort_order, tag = excluded.tag;
insert into public.site_content (page, block_key, original, sort_order, tag) values
  ('about-koinonia-faq/index.html', '28', 'Students are asked to participate in our opening meeting and all three sessions, and are expected to abide by the code of conduct to the best of their abilities. There will be minimal out-of-class homework.', 28, 'p')
on conflict (page, block_key) do update set original = excluded.original,
  sort_order = excluded.sort_order, tag = excluded.tag;
insert into public.site_content (page, block_key, original, sort_order, tag) values
  ('about-koinonia-faq/index.html', '29', 'What is the cost?', 29, 'h4')
on conflict (page, block_key) do update set original = excluded.original,
  sort_order = excluded.sort_order, tag = excluded.tag;
insert into public.site_content (page, block_key, original, sort_order, tag) values
  ('about-koinonia-faq/index.html', '30', 'There is a semester fee of $35 per family. Some classes may have additional fees, which will be clearly stated on the class schedule and at signup.', 30, 'p')
on conflict (page, block_key) do update set original = excluded.original,
  sort_order = excluded.sort_order, tag = excluded.tag;
insert into public.site_content (page, block_key, original, sort_order, tag) values
  ('about-koinonia-faq/index.html', '31', 'When do classes meet?', 31, 'h4')
on conflict (page, block_key) do update set original = excluded.original,
  sort_order = excluded.sort_order, tag = excluded.tag;
insert into public.site_content (page, block_key, original, sort_order, tag) values
  ('about-koinonia-faq/index.html', '32', 'Classes meet Thursday afternoons from 12:30 pm – 4:00 pm. Our Café area opens at 11:45 for our families to bring a lunch and eat together if they choose.', 32, 'p')
on conflict (page, block_key) do update set original = excluded.original,
  sort_order = excluded.sort_order, tag = excluded.tag;
insert into public.site_content (page, block_key, original, sort_order, tag) values
  ('about-koinonia-faq/index.html', '33', 'What is the schedule?', 33, 'h4')
on conflict (page, block_key) do update set original = excluded.original,
  sort_order = excluded.sort_order, tag = excluded.tag;
insert into public.site_content (page, block_key, original, sort_order, tag) values
  ('about-koinonia-faq/index.html', '34', 'Fall 2026*', 34, 'h2')
on conflict (page, block_key) do update set original = excluded.original,
  sort_order = excluded.sort_order, tag = excluded.tag;
insert into public.site_content (page, block_key, original, sort_order, tag) values
  ('about-koinonia-faq/index.html', '35', 'August 6-13 Class sign-ups are open', 35, 'p')
on conflict (page, block_key) do update set original = excluded.original,
  sort_order = excluded.sort_order, tag = excluded.tag;
insert into public.site_content (page, block_key, original, sort_order, tag) values
  ('about-koinonia-faq/index.html', '36', 'August 15- Mom’s Tea and Information Meeting', 36, 'p')
on conflict (page, block_key) do update set original = excluded.original,
  sort_order = excluded.sort_order, tag = excluded.tag;
insert into public.site_content (page, block_key, original, sort_order, tag) values
  ('about-koinonia-faq/index.html', '37', 'August 20- First Day of Classes!', 37, 'p')
on conflict (page, block_key) do update set original = excluded.original,
  sort_order = excluded.sort_order, tag = excluded.tag;
insert into public.site_content (page, block_key, original, sort_order, tag) values
  ('about-koinonia-faq/index.html', '38', 'October 1 & 8- Fall Break (no classes)', 38, 'p')
on conflict (page, block_key) do update set original = excluded.original,
  sort_order = excluded.sort_order, tag = excluded.tag;
insert into public.site_content (page, block_key, original, sort_order, tag) values
  ('about-koinonia-faq/index.html', '39', 'November 21- End of Semester Showcase', 39, 'p')
on conflict (page, block_key) do update set original = excluded.original,
  sort_order = excluded.sort_order, tag = excluded.tag;
insert into public.site_content (page, block_key, original, sort_order, tag) values
  ('about-koinonia-faq/index.html', '40', 'November 26- Thanksgiving Break', 40, 'p')
on conflict (page, block_key) do update set original = excluded.original,
  sort_order = excluded.sort_order, tag = excluded.tag;
insert into public.site_content (page, block_key, original, sort_order, tag) values
  ('about-koinonia-faq/index.html', '41', 'December 3- Christmas Party', 41, 'p')
on conflict (page, block_key) do update set original = excluded.original,
  sort_order = excluded.sort_order, tag = excluded.tag;
insert into public.site_content (page, block_key, original, sort_order, tag) values
  ('about-koinonia-faq/index.html', '42', '*Dates are subject to change. See our full calendar [here](../calendar/).', 42, 'p')
on conflict (page, block_key) do update set original = excluded.original,
  sort_order = excluded.sort_order, tag = excluded.tag;
insert into public.site_content (page, block_key, original, sort_order, tag) values
  ('about-koinonia-faq/index.html', '43', 'Where do we meet?', 43, 'h4')
on conflict (page, block_key) do update set original = excluded.original,
  sort_order = excluded.sort_order, tag = excluded.tag;
insert into public.site_content (page, block_key, original, sort_order, tag) values
  ('about-koinonia-faq/index.html', '44', 'North Mountain Church
10202 N. Cave Creek Road
Phoenix, AZ 85020', 44, 'p')
on conflict (page, block_key) do update set original = excluded.original,
  sort_order = excluded.sort_order, tag = excluded.tag;
insert into public.site_content (page, block_key, original, sort_order, tag) values
  ('about-koinonia-faq/index.html', '45', 'Who’s in charge?', 45, 'h4')
on conflict (page, block_key) do update set original = excluded.original,
  sort_order = excluded.sort_order, tag = excluded.tag;
insert into public.site_content (page, block_key, original, sort_order, tag) values
  ('about-koinonia-faq/index.html', '46', 'We currently have a 4-person leadership team. They are highly experienced homeschool moms, working behind the scenes to make sure everything is organized and communicated well. You can meet the leadership team [here](../about/) and send us your questions or comments [here](../contact/).', 46, 'p')
on conflict (page, block_key) do update set original = excluded.original,
  sort_order = excluded.sort_order, tag = excluded.tag;
insert into public.site_content (page, block_key, original, sort_order, tag) values
  ('about-koinonia-faq/index.html', '47', 'As a ministry of North Mountain Church we also submit ourselves to their standards and leaders.', 47, 'p')
on conflict (page, block_key) do update set original = excluded.original,
  sort_order = excluded.sort_order, tag = excluded.tag;
insert into public.site_content (page, block_key, original, sort_order, tag) values
  ('about-koinonia-faq/index.html', '48', 'How do I get started?', 48, 'h4')
on conflict (page, block_key) do update set original = excluded.original,
  sort_order = excluded.sort_order, tag = excluded.tag;
insert into public.site_content (page, block_key, original, sort_order, tag) values
  ('about-koinonia-faq/index.html', '49', 'We have a three stage enrollment process for new members:', 49, 'p')
on conflict (page, block_key) do update set original = excluded.original,
  sort_order = excluded.sort_order, tag = excluded.tag;
insert into public.site_content (page, block_key, original, sort_order, tag) values
  ('about-koinonia-faq/index.html', '50', '1.       Apply: Fill out an [Application for Membership](../apply/). You will then be contacted by a member of our leadership team to set up a time to meet in person or over Zoom. We are working to develop a tight-knit community, so we want to get to know you and make sure we are a good fit for each other.', 50, 'p')
on conflict (page, block_key) do update set original = excluded.original,
  sort_order = excluded.sort_order, tag = excluded.tag;
insert into public.site_content (page, block_key, original, sort_order, tag) values
  ('about-koinonia-faq/index.html', '51', '2.       Register: After your application is approved, you can fill out our [New Family Registration](../newfamilyregistration/). Once we have your registration, you will be contacted by the leadership team to discuss where you would best fit as a teacher or helper.', 51, 'p')
on conflict (page, block_key) do update set original = excluded.original,
  sort_order = excluded.sort_order, tag = excluded.tag;
insert into public.site_content (page, block_key, original, sort_order, tag) values
  ('about-koinonia-faq/index.html', '52', '3.       Sign up: Finally, after all our classes are in order, you will be invited to sign up your children for their individual classes.', 52, 'p')
on conflict (page, block_key) do update set original = excluded.original,
  sort_order = excluded.sort_order, tag = excluded.tag;
insert into public.site_content (page, block_key, original, sort_order, tag) values
  ('about-koinonia-faq/index.html', '53', 'What if I’m already a member?', 53, 'h4')
on conflict (page, block_key) do update set original = excluded.original,
  sort_order = excluded.sort_order, tag = excluded.tag;
insert into public.site_content (page, block_key, original, sort_order, tag) values
  ('about-koinonia-faq/index.html', '54', 'Returning members only need to fill out a [Returning Family Registration](https://koinoniaphx.com/returning-family-registration/?frame-nonce=0252e36134), submit class ideas, and sign up your children for their individual classes.', 54, 'p')
on conflict (page, block_key) do update set original = excluded.original,
  sort_order = excluded.sort_order, tag = excluded.tag;
insert into public.site_content (page, block_key, original, sort_order, tag) values
  ('about-koinonia-faq/index.html', '55', 'This was our first semester at Koinonia but we were immediately at home with this great group of families. Our boys have good friends among the other kids and are getting to know even more kids in other families. I enjoyed the fellowship with the other moms in a relaxed environment of spiritual unity.', 55, 'p')
on conflict (page, block_key) do update set original = excluded.original,
  sort_order = excluded.sort_order, tag = excluded.tag;
insert into public.site_content (page, block_key, original, sort_order, tag) values
  ('our-beliefs/index.html', '1', 'Koinonia Homeschool Group is a ministry of North Mountain Church. Please see their Statement of Faith [here](https://www.northmountainchurch.org/beliefs).', 1, 'p')
on conflict (page, block_key) do update set original = excluded.original,
  sort_order = excluded.sort_order, tag = excluded.tag;
insert into public.site_content (page, block_key, original, sort_order, tag) values
  ('our-beliefs/index.html', '2', 'Statement of Faith', 2, 'h4')
on conflict (page, block_key) do update set original = excluded.original,
  sort_order = excluded.sort_order, tag = excluded.tag;
insert into public.site_content (page, block_key, original, sort_order, tag) values
  ('our-beliefs/index.html', '3', 'We believe the Bible to be the inspired, infallible, Word of God, authoritative in matters of faith and life. (2 Tim. 3:16-17, 1 Pet. 1:20-21).', 3, 'li')
on conflict (page, block_key) do update set original = excluded.original,
  sort_order = excluded.sort_order, tag = excluded.tag;
insert into public.site_content (page, block_key, original, sort_order, tag) values
  ('our-beliefs/index.html', '4', 'We believe that there is one God, eternally existent in three persons: Father, Son and Holy Spirit (Deut. 6:4, 1 Tim. 1:17, Mat. 28:19-20).', 4, 'li')
on conflict (page, block_key) do update set original = excluded.original,
  sort_order = excluded.sort_order, tag = excluded.tag;
insert into public.site_content (page, block_key, original, sort_order, tag) values
  ('our-beliefs/index.html', '5', 'We believe in the deity and humanity of Christ (Phil. 2:6-8), in His virgin birth (Mat. 1:22-23), in His sinless life (Heb. 4:15), in His miracles (John 22:24-25), in His vicarious and atoning death through His shed blood (Rom. 5:8-9) and in His bodily resurrection (John 20:25-29) and in His personal return in power and glory (1 Thes. 4:16).', 5, 'li')
on conflict (page, block_key) do update set original = excluded.original,
  sort_order = excluded.sort_order, tag = excluded.tag;
insert into public.site_content (page, block_key, original, sort_order, tag) values
  ('our-beliefs/index.html', '6', 'We believe in the present ministry of the Holy Spirit, by who’s indwelling the Christian is enabled to live a godly life (Gal. 5:16, Rom. 8:9).', 6, 'li')
on conflict (page, block_key) do update set original = excluded.original,
  sort_order = excluded.sort_order, tag = excluded.tag;
insert into public.site_content (page, block_key, original, sort_order, tag) values
  ('our-beliefs/index.html', '7', 'We believe that all those who die in God’s grace through faith are assured eternal salvation; those who die in a state of sin and unbelief suffer the punishment of Hell (Eph. 2:8, 2 Pet. 2:4-10).', 7, 'li')
on conflict (page, block_key) do update set original = excluded.original,
  sort_order = excluded.sort_order, tag = excluded.tag;
insert into public.site_content (page, block_key, original, sort_order, tag) values
  ('our-beliefs/index.html', '8', 'We believe in the spiritual unity of believers in our Lord Jesus Christ, with equality across racial, gender, and class differences (Gal. 4:26-28).', 8, 'li')
on conflict (page, block_key) do update set original = excluded.original,
  sort_order = excluded.sort_order, tag = excluded.tag;
insert into public.site_content (page, block_key, original, sort_order, tag) values
  ('our-beliefs/index.html', '9', 'We believe that marriage is the uniting of one man and one woman in a single, exclusive union (Gen. 2:18-25). We believe that God intends sexual intimacy to occur only between a man and a woman who are married to each other (Heb. 13:4). We believe that any form of sexual immorality (including sex outside marriage, adultery, fornication, homosexual behavior, bisexual conduct, bestiality, incest, and use of pornography) is sinful and offensive to God (1 Cor. 6:9-10).', 9, 'li')
on conflict (page, block_key) do update set original = excluded.original,
  sort_order = excluded.sort_order, tag = excluded.tag;
insert into public.site_content (page, block_key, original, sort_order, tag) values
  ('our-beliefs/index.html', '10', 'We believe that God wonderfully and immutably creates each person as male or female. These two distinct, complementary genders together reflect the image and nature of God (Gen. 1:26-27). Rejection of one’s biological sex is a rejection of the image of God within that person.', 10, 'li')
on conflict (page, block_key) do update set original = excluded.original,
  sort_order = excluded.sort_order, tag = excluded.tag;
insert into public.site_content (page, block_key, original, sort_order, tag) values
  ('our-beliefs/index.html', '11', 'We believe that every person must be afforded compassion, love, kindness, respect, and dignity. (Luke 6:31).', 11, 'li')
on conflict (page, block_key) do update set original = excluded.original,
  sort_order = excluded.sort_order, tag = excluded.tag;
insert into public.site_content (page, block_key, original, sort_order, tag) values
  ('our-beliefs/index.html', '12', 'We believe that hateful and harassing behavior or attitudes directed toward any individual are to be repudiated and are not in accord with the Scriptures (Prov. 22:10; Rom. 14:9).', 12, 'li')
on conflict (page, block_key) do update set original = excluded.original,
  sort_order = excluded.sort_order, tag = excluded.tag;
insert into public.site_content (page, block_key, original, sort_order, tag) values
  ('our-beliefs/index.html', '13', 'We believe that the Bible itself speaks with final authority concerning truth, morality, and the proper conduct of mankind, and is the sole and final source of all that we believe (2 Tim. 3:16).', 13, 'li')
on conflict (page, block_key) do update set original = excluded.original,
  sort_order = excluded.sort_order, tag = excluded.tag;
insert into public.site_content (page, block_key, original, sort_order, tag) values
  ('our-beliefs/index.html', '14', 'We believe that God designed the family in his perfect wisdom. He has assigned the husband as the head, wife as the helpmeet, and children to honor their parents. As wives and children, we honor the men in our lives, our fathers and husbands, and respect their role as leaders of our homes. We look to them as spiritual leaders and role models and seek out their counsel and wisdom in all things. Likewise, as fathers, we love our wives and children, making decisions for the benefit of the whole family. (Prov. 13:1, Eph. 5:22-30, Eph. 6:1-3, Gen. 2:18)', 14, 'li')
on conflict (page, block_key) do update set original = excluded.original,
  sort_order = excluded.sort_order, tag = excluded.tag;
insert into public.site_content (page, block_key, original, sort_order, tag) values
  ('our-beliefs/index.html', '15', 'Code of Conduct', 15, 'h4')
on conflict (page, block_key) do update set original = excluded.original,
  sort_order = excluded.sort_order, tag = excluded.tag;
insert into public.site_content (page, block_key, original, sort_order, tag) values
  ('our-beliefs/index.html', '16', '-Christ-like Behavior in the Classroom-', 16, 'p')
on conflict (page, block_key) do update set original = excluded.original,
  sort_order = excluded.sort_order, tag = excluded.tag;
insert into public.site_content (page, block_key, original, sort_order, tag) values
  ('our-beliefs/index.html', '17', 'Live in a pure and Christ-like manner. (But among you there must not be even a hint of sexual immorality, or of any kind of impurity, or of greed, because these are improper for God’s holy people. – Eph. 5:3) Please see the Statement of Faith for a more comprehensive explanation of our beliefs.', 17, 'p')
on conflict (page, block_key) do update set original = excluded.original,
  sort_order = excluded.sort_order, tag = excluded.tag;
insert into public.site_content (page, block_key, original, sort_order, tag) values
  ('our-beliefs/index.html', '18', 'Use self-control in your actions and language.  Do not indulge in gossip, slander, and foul language.  (Nor should there be obscenity, foolish talk or coarse joking, which are out of place, but rather thanksgiving.  – Eph. 5:4) AND (Finally, brothers, whatever is true, whatever is noble, whatever is right, whatever is pure, whatever is lovely, whatever is admirable – if anything is excellent or praiseworthy – think about such things. – Phil. 4:8)', 18, 'p')
on conflict (page, block_key) do update set original = excluded.original,
  sort_order = excluded.sort_order, tag = excluded.tag;
insert into public.site_content (page, block_key, original, sort_order, tag) values
  ('our-beliefs/index.html', '19', 'Honor those around you by respecting them, encouraging them and avoiding words or actions that would be harmful. (Do not let any unwholesome talk come out of your mouths, but only what is helpful for building others up according to their needs, that it may benefit those who listen – Eph. 4:29)', 19, 'p')
on conflict (page, block_key) do update set original = excluded.original,
  sort_order = excluded.sort_order, tag = excluded.tag;
insert into public.site_content (page, block_key, original, sort_order, tag) values
  ('our-beliefs/index.html', '20', 'Speak the truth to others in love. (Instead, speak the truth in love.  – Eph. 4:15)', 20, 'p')
on conflict (page, block_key) do update set original = excluded.original,
  sort_order = excluded.sort_order, tag = excluded.tag;
insert into public.site_content (page, block_key, original, sort_order, tag) values
  ('our-beliefs/index.html', '21', 'Regard yourself with humility. (Do nothing out of selfish ambition or vain conceit. Rather, in humility value others above yourselves, not looking to your own interests but each of you to the interests of the others. – Phil. 2: 3-4) AND (If anyone thinks he is something when he is nothing, he deceives himself. Each one should test his own actions. Then he can take pride in himself, without comparing himself to somebody else, for each one should carry his own load. – Gal. 6: 3-5)', 21, 'p')
on conflict (page, block_key) do update set original = excluded.original,
  sort_order = excluded.sort_order, tag = excluded.tag;
insert into public.site_content (page, block_key, original, sort_order, tag) values
  ('our-beliefs/index.html', '22', 'Put others first and treat one another with love. (Do not use your freedom to indulge the sinful nature; rather, serve one another in love. – Gal. 5: 13) AND (Carry each other’s burdens, and in this way you will fulfill the law of Christ. – Gal. 6: 2)', 22, 'p')
on conflict (page, block_key) do update set original = excluded.original,
  sort_order = excluded.sort_order, tag = excluded.tag;
insert into public.site_content (page, block_key, original, sort_order, tag) values
  ('our-beliefs/index.html', '23', 'Remember that we represent Christ and be a good witness to others.  (Our conscience testifies that we have conducted ourselves in the world, and especially in our relations with you, with integrity and godly sincerity.  – 2 Cor. 1: 12)', 23, 'p')
on conflict (page, block_key) do update set original = excluded.original,
  sort_order = excluded.sort_order, tag = excluded.tag;
insert into public.site_content (page, block_key, original, sort_order, tag) values
  ('our-beliefs/index.html', '24', '–Respect for Authority–', 24, 'p')
on conflict (page, block_key) do update set original = excluded.original,
  sort_order = excluded.sort_order, tag = excluded.tag;
insert into public.site_content (page, block_key, original, sort_order, tag) values
  ('our-beliefs/index.html', '25', 'Respect the authority God has placed in your life. (Now we ask you, brothers, to respect those who work hard among you, who are over you in the Lord and who admonish you. Hold them in the highest regard in love because of their work. Live in peace with one another. – 1 Thes. 5:12-13)', 25, 'p')
on conflict (page, block_key) do update set original = excluded.original,
  sort_order = excluded.sort_order, tag = excluded.tag;
insert into public.site_content (page, block_key, original, sort_order, tag) values
  ('our-beliefs/index.html', '26', 'Refrain from gossiping about an issue with others thus spreading disunity and mistrust among your fellow students. (Remind the people to be subject to rulers and authorities, to be obedient, to be ready to do whatever is good, to slander no one, to be peaceable and considerate, and to show true humility toward all men. – Titus 3:1)', 26, 'p')
on conflict (page, block_key) do update set original = excluded.original,
  sort_order = excluded.sort_order, tag = excluded.tag;
insert into public.site_content (page, block_key, original, sort_order, tag) values
  ('our-beliefs/index.html', '27', '–Resolving conflict in a Christ-honoring manner–', 27, 'p')
on conflict (page, block_key) do update set original = excluded.original,
  sort_order = excluded.sort_order, tag = excluded.tag;
insert into public.site_content (page, block_key, original, sort_order, tag) values
  ('our-beliefs/index.html', '28', 'For the cause of Christ and Christian unity, do not take offense, and forgive without being asked. (A person’s wisdom yields patience; it is to one’s glory to overlook an offense. – Prov. 19:11)', 28, 'p')
on conflict (page, block_key) do update set original = excluded.original,
  sort_order = excluded.sort_order, tag = excluded.tag;
insert into public.site_content (page, block_key, original, sort_order, tag) values
  ('our-beliefs/index.html', '29', 'Encourage one another to handle issues discreetly and quickly without involving others and without gossip. (Without wood a fire goes out; without gossip a quarrel dies down. – Prov. 26:20)', 29, 'p')
on conflict (page, block_key) do update set original = excluded.original,
  sort_order = excluded.sort_order, tag = excluded.tag;
insert into public.site_content (page, block_key, original, sort_order, tag) values
  ('our-beliefs/index.html', '30', 'When conflict arises it should be privately discussed immediately between the individuals.  If the matter is not resolved, the individuals should meet quickly with the teacher.  If there is no resolution, then the matter will be taken to the leadership team.  (“If your brother or sister sins, go and point out their fault, just between the two of you. If they listen to you, you have won them over.  But if they will not listen, take one or two others along, so that every matter may be established by the testimony of two or three witnesses.’ If they still refuse to listen, tell it to the church. – Mat. 18:15-17)', 30, 'p')
on conflict (page, block_key) do update set original = excluded.original,
  sort_order = excluded.sort_order, tag = excluded.tag;
insert into public.site_content (page, block_key, original, sort_order, tag) values
  ('our-beliefs/index.html', '31', 'Forgive one another and move on. (Bear with each other and forgive one another if any of you has a grievance against someone. Forgive as the Lord forgave you.  And over all these virtues put on love, which binds them all together in perfect unity. – Col. 3: 13-14)', 31, 'p')
on conflict (page, block_key) do update set original = excluded.original,
  sort_order = excluded.sort_order, tag = excluded.tag;
insert into public.site_content (page, block_key, original, sort_order, tag) values
  ('our-beliefs/index.html', '32', '–Excellence for the Glory of God–', 32, 'p')
on conflict (page, block_key) do update set original = excluded.original,
  sort_order = excluded.sort_order, tag = excluded.tag;
insert into public.site_content (page, block_key, original, sort_order, tag) values
  ('our-beliefs/index.html', '33', 'Work with your whole heart not for the approval of men but for the glory of God.  (We are not trying to please men but God, who tests our hearts. – I Thes. 2: 4b)', 33, 'p')
on conflict (page, block_key) do update set original = excluded.original,
  sort_order = excluded.sort_order, tag = excluded.tag;
insert into public.site_content (page, block_key, original, sort_order, tag) values
  ('our-beliefs/index.html', '34', 'Participate with a willing attitude, self-discipline, integrity and humility. (Each one should use whatever gift he has received to serve others…If anyone serves, he should do it with the strength God provides, so that in all things God may be praised. – 1 Pet. 4: 10-11a)', 34, 'p')
on conflict (page, block_key) do update set original = excluded.original,
  sort_order = excluded.sort_order, tag = excluded.tag;
insert into public.site_content (page, block_key, original, sort_order, tag) values
  ('our-beliefs/index.html', '35', 'Working with others and for yourself with all diligence for the glory of God. (Whatever you do, work at it with all your heart, as working for the Lord, not for men, since you know that you will receive an inheritance from the Lord as a reward. It is the Lord Christ you are serving. – Col. 3:23)', 35, 'p')
on conflict (page, block_key) do update set original = excluded.original,
  sort_order = excluded.sort_order, tag = excluded.tag;
insert into public.site_content (page, block_key, original, sort_order, tag) values
  ('our-beliefs/index.html', '36', 'In everything you do be honest never cheating or lying but honoring the Lord in words, deeds and actions. (The integrity of the upright guides them, but the unfaithful are destroyed by their duplicity. – Prov. 11:3)', 36, 'p')
on conflict (page, block_key) do update set original = excluded.original,
  sort_order = excluded.sort_order, tag = excluded.tag;
insert into public.site_content (page, block_key, original, sort_order, tag) values
  ('about/index.html', '1', 'Who We Are', 1, 'h2')
on conflict (page, block_key) do update set original = excluded.original,
  sort_order = excluded.sort_order, tag = excluded.tag;
insert into public.site_content (page, block_key, original, sort_order, tag) values
  ('about/index.html', '2', 'We started as three homeschool moms in Phoenix, Arizona with a vision for a Christ-centered homeschool community for our kids and ourselves. We each come from different backgrounds and paths in life, but we’ve been brought together by our love for Jesus Christ and our passion for our families and our kids’ education. We believe that, with our children, comes a responsibility to be their primary educator. Part of that is teaching them to participate in the body of Christ (1 Corinthians 12: 12-31) and the community in which we live (Jeremiah 29:7). We also want to make the most of our different gifts, and recognize our own need as moms to have community and encourage each other.', 2, 'p')
on conflict (page, block_key) do update set original = excluded.original,
  sort_order = excluded.sort_order, tag = excluded.tag;
insert into public.site_content (page, block_key, original, sort_order, tag) values
  ('about/index.html', '3', 'Hi, I’m Sharon Rodriguez. I am a missionary kid from Africa who was homeschooled on and off for most of my childhood. My husband, Steve, and I have been schooling our three boys at home for 13 years. We just launched our oldest son into the college years and are headed into HS with our second and MS with our third. We love the Lord and we love people!! Community and hospitality are huge priorities. We love helping others find their God-given giftedness to use in the Body of Christ. I love reading, sewing, organizing, teaching and THEATRE!', 3, 'p')
on conflict (page, block_key) do update set original = excluded.original,
  sort_order = excluded.sort_order, tag = excluded.tag;
insert into public.site_content (page, block_key, original, sort_order, tag) values
  ('about/index.html', '4', 'Sharon Rodriguez', 4, 'h2')
on conflict (page, block_key) do update set original = excluded.original,
  sort_order = excluded.sort_order, tag = excluded.tag;
insert into public.site_content (page, block_key, original, sort_order, tag) values
  ('about/index.html', '5', '–Events Coordinator, Facilities Liaison, Treasurer', 5, 'p')
on conflict (page, block_key) do update set original = excluded.original,
  sort_order = excluded.sort_order, tag = excluded.tag;
insert into public.site_content (page, block_key, original, sort_order, tag) values
  ('about/index.html', '6', 'Valerie Denny', 6, 'h2')
on conflict (page, block_key) do update set original = excluded.original,
  sort_order = excluded.sort_order, tag = excluded.tag;
insert into public.site_content (page, block_key, original, sort_order, tag) values
  ('about/index.html', '7', '-Registrar', 7, 'p')
on conflict (page, block_key) do update set original = excluded.original,
  sort_order = excluded.sort_order, tag = excluded.tag;
insert into public.site_content (page, block_key, original, sort_order, tag) values
  ('about/index.html', '8', 'Hi, I’m Valerie Denny. I love coffee, mystery novels, all kinds of art, and jogging. I was homeschooled from 1st grade all the way through high school. My husband was also homeschooled for most of his education, and so it seemed the natural choice for us to homeschool our own children. We have two boys, both of whom have now reached the high school years and will soon be ready to launch. I’m passionate about teaching the Bible, acting, literature, and handicrafts.', 8, 'p')
on conflict (page, block_key) do update set original = excluded.original,
  sort_order = excluded.sort_order, tag = excluded.tag;
insert into public.site_content (page, block_key, original, sort_order, tag) values
  ('about/index.html', '9', 'Hi, I’m Candace Hershberger. I am a pastor’s kid who was homeschooled just a couple years while growing up. Back then I thought it was the worst thing ever, but now I am so grateful for the time my parents invested in that way of schooling. We have been homeschooling our three kids since COVID and cannot be more thankful for that very big God nudge to do it!  I have written a devotional called, Miraculous Joy, all about our family’s 7 year journey through my husband’s cancer. I believe even in the hard times of life Jesus is working and we can find joy in it all.  I love coffee or tea, reading, doing puzzles, crafting and hiking. I have a BFA in photography and love mixed media art. Also all of us Hershbergers are black belts in taekwondo!', 9, 'p')
on conflict (page, block_key) do update set original = excluded.original,
  sort_order = excluded.sort_order, tag = excluded.tag;
insert into public.site_content (page, block_key, original, sort_order, tag) values
  ('about/index.html', '10', 'Candace Hershberger', 10, 'h2')
on conflict (page, block_key) do update set original = excluded.original,
  sort_order = excluded.sort_order, tag = excluded.tag;
insert into public.site_content (page, block_key, original, sort_order, tag) values
  ('about/index.html', '11', '–Administrator and Director', 11, 'p')
on conflict (page, block_key) do update set original = excluded.original,
  sort_order = excluded.sort_order, tag = excluded.tag;
insert into public.site_content (page, block_key, original, sort_order, tag) values
  ('about/index.html', '12', 'Katie Lanting', 12, 'h2')
on conflict (page, block_key) do update set original = excluded.original,
  sort_order = excluded.sort_order, tag = excluded.tag;
insert into public.site_content (page, block_key, original, sort_order, tag) values
  ('about/index.html', '13', '-Student Leadership Coordinator', 13, 'p')
on conflict (page, block_key) do update set original = excluded.original,
  sort_order = excluded.sort_order, tag = excluded.tag;
insert into public.site_content (page, block_key, original, sort_order, tag) values
  ('about/index.html', '14', 'Hi, I’m Katie Lanting. I am wife to Cooper and mom of two boys and have been homeschooling since my oldest was in kindergarten. Although I went to public school and public university, I love homeschooling and Christian education. I have a Bachelor’s degree from Northern Arizona University in Elementary Education, and a Masters from the same institution in English Creative Writing. I teach 6th grade part time at Highlands Latin School. I’m obsessed with Jane Austen and all things British, chocolate, coffee, and nerdy pastimes. When I’m not  teaching, you can find me in community theater productions (I’ve been in close to 30!), or with my nose stuck in a good book.', 14, 'p')
on conflict (page, block_key) do update set original = excluded.original,
  sort_order = excluded.sort_order, tag = excluded.tag;
insert into public.site_content (page, block_key, original, sort_order, tag) values
  ('contact/index.html', '1', 'Get in Touch', 1, 'h2')
on conflict (page, block_key) do update set original = excluded.original,
  sort_order = excluded.sort_order, tag = excluded.tag;
insert into public.site_content (page, block_key, original, sort_order, tag) values
  ('contact/index.html', '2', 'Meeting Address', 2, 'h2')
on conflict (page, block_key) do update set original = excluded.original,
  sort_order = excluded.sort_order, tag = excluded.tag;
insert into public.site_content (page, block_key, original, sort_order, tag) values
  ('contact/index.html', '3', 'North Mountain Church', 3, 'p')
on conflict (page, block_key) do update set original = excluded.original,
  sort_order = excluded.sort_order, tag = excluded.tag;
insert into public.site_content (page, block_key, original, sort_order, tag) values
  ('contact/index.html', '4', '10202 N Cave Creek Rd,', 4, 'p')
on conflict (page, block_key) do update set original = excluded.original,
  sort_order = excluded.sort_order, tag = excluded.tag;
insert into public.site_content (page, block_key, original, sort_order, tag) values
  ('contact/index.html', '5', 'Phoenix, AZ 85020', 5, 'p')
on conflict (page, block_key) do update set original = excluded.original,
  sort_order = excluded.sort_order, tag = excluded.tag;
insert into public.site_content (page, block_key, original, sort_order, tag) values
  ('contact/index.html', '6', 'Send Us a Message', 6, 'h2')
on conflict (page, block_key) do update set original = excluded.original,
  sort_order = excluded.sort_order, tag = excluded.tag;
insert into public.site_content (page, block_key, original, sort_order, tag) values
  ('contact/index.html', '7', '[← Back](../contact/)', 7, 'p')
on conflict (page, block_key) do update set original = excluded.original,
  sort_order = excluded.sort_order, tag = excluded.tag;
insert into public.site_content (page, block_key, original, sort_order, tag) values
  ('contact/index.html', '8', 'Thank you for your response. ✨', 8, 'h4')
on conflict (page, block_key) do update set original = excluded.original,
  sort_order = excluded.sort_order, tag = excluded.tag;
insert into public.site_content (page, block_key, original, sort_order, tag) values
  ('registration/index.html', '1', 'If you are a new family and your application has been approved by our leadership team you may register [here.](../newfamilyregistration/)', 1, 'p')
on conflict (page, block_key) do update set original = excluded.original,
  sort_order = excluded.sort_order, tag = excluded.tag;
insert into public.site_content (page, block_key, original, sort_order, tag) values
  ('registration/index.html', '2', 'If you are a returning family you may register [here.](../returning-family-registration/)', 2, 'p')
on conflict (page, block_key) do update set original = excluded.original,
  sort_order = excluded.sort_order, tag = excluded.tag;
insert into public.site_content (page, block_key, original, sort_order, tag) values
  ('registration/index.html', '3', 'Registration is currently closed, but you are welcome to check back later in the year about our next semester.', 3, 'p')
on conflict (page, block_key) do update set original = excluded.original,
  sort_order = excluded.sort_order, tag = excluded.tag;
insert into public.site_content (page, block_key, original, sort_order, tag) values
  ('returning-family-registration/index.html', '1', '-Fall 2026-', 1, 'h2')
on conflict (page, block_key) do update set original = excluded.original,
  sort_order = excluded.sort_order, tag = excluded.tag;
insert into public.site_content (page, block_key, original, sort_order, tag) values
  ('returning-family-registration/index.html', '2', 'This form is for families that are existing members of Koinonia Homeschool Group. If you are not an existing member you can learn how to become one on our [About](../about-koinonia-faq/) page.', 2, 'p')
on conflict (page, block_key) do update set original = excluded.original,
  sort_order = excluded.sort_order, tag = excluded.tag;
insert into public.site_content (page, block_key, original, sort_order, tag) values
  ('returning-family-registration/index.html', '3', '“Go To Checkout” will take you to the North Mountain Church website’s donation page to checkout. Pick “Koinonia Homeschool Group” from the drop down and enter $35 per family.', 3, 'p')
on conflict (page, block_key) do update set original = excluded.original,
  sort_order = excluded.sort_order, tag = excluded.tag;
insert into public.site_content (page, block_key, original, sort_order, tag) values
  ('returning-family-registration/index.html', '4', '[](context.item.anchor)', 4, 'li')
on conflict (page, block_key) do update set original = excluded.original,
  sort_order = excluded.sort_order, tag = excluded.tag;
insert into public.site_content (page, block_key, original, sort_order, tag) values
  ('newfamilyregistration/index.html', '1', 'This form is for families whose application has been approved and who are starting their first semester with Koinonia Homeschool Group. If you would like to apply for membership, you can do so [here](../apply/).', 1, 'p')
on conflict (page, block_key) do update set original = excluded.original,
  sort_order = excluded.sort_order, tag = excluded.tag;
insert into public.site_content (page, block_key, original, sort_order, tag) values
  ('newfamilyregistration/index.html', '2', '“Go To Checkout” will take you to the North Mountain Church website’s donation page to checkout. Pick “Koinonia Homeschool Group” from the drop down and enter $35 per family.', 2, 'p')
on conflict (page, block_key) do update set original = excluded.original,
  sort_order = excluded.sort_order, tag = excluded.tag;
insert into public.site_content (page, block_key, original, sort_order, tag) values
  ('newfamilyregistration/index.html', '3', '[](context.item.anchor)', 3, 'li')
on conflict (page, block_key) do update set original = excluded.original,
  sort_order = excluded.sort_order, tag = excluded.tag;
insert into public.site_content (page, block_key, original, sort_order, tag) values
  ('classes-signup/index.html', '1', 'Descriptions of classes can be found [here](../class-descriptions/). Class sign ups will be open 8/6 – 8/13', 1, 'p')
on conflict (page, block_key) do update set original = excluded.original,
  sort_order = excluded.sort_order, tag = excluded.tag;
insert into public.site_content (page, block_key, original, sort_order, tag) values
  ('classes-signup/index.html', '2', '[← Back](../classes-signup/)', 2, 'p')
on conflict (page, block_key) do update set original = excluded.original,
  sort_order = excluded.sort_order, tag = excluded.tag;
insert into public.site_content (page, block_key, original, sort_order, tag) values
  ('classes-signup/index.html', '3', 'Thank you for signing up for classes!', 3, 'h4')
on conflict (page, block_key) do update set original = excluded.original,
  sort_order = excluded.sort_order, tag = excluded.tag;
insert into public.site_content (page, block_key, original, sort_order, tag) values
  ('classes-signup/index.html', '4', '[](context.item.anchor)', 4, 'li')
on conflict (page, block_key) do update set original = excluded.original,
  sort_order = excluded.sort_order, tag = excluded.tag;
insert into public.site_content (page, block_key, original, sort_order, tag) values
  ('classes-signup/index.html', '5', '*Class has required materials', 5, 'p')
on conflict (page, block_key) do update set original = excluded.original,
  sort_order = excluded.sort_order, tag = excluded.tag;
insert into public.site_content (page, block_key, original, sort_order, tag) values
  ('classes-signup/index.html', '6', 'Some classes include a fee to cover the cost of materials for the class. We do all we can to keep the fees minimal. Fees will be collected at the Mom’s Tea and Information Meeting.', 6, 'p')
on conflict (page, block_key) do update set original = excluded.original,
  sort_order = excluded.sort_order, tag = excluded.tag;
insert into public.site_content (page, block_key, original, sort_order, tag) values
  ('classes-signup/index.html', '7', 'Please do not let money be the deciding factor in which classes your family chooses. If you can’t afford the fees for a class your child wants, please mention it to the leadership team and we will be happy to work with you.', 7, 'p')
on conflict (page, block_key) do update set original = excluded.original,
  sort_order = excluded.sort_order, tag = excluded.tag;
insert into public.site_content (page, block_key, original, sort_order, tag) values
  ('classes-signup/index.html', '8', 'Trust me, we’ll be very nice about it.', 8, 'p')
on conflict (page, block_key) do update set original = excluded.original,
  sort_order = excluded.sort_order, tag = excluded.tag;
insert into public.site_content (page, block_key, original, sort_order, tag) values
  ('class-proposal-form/index.html', '1', 'This form is for families that are existing members of Koinonia Homeschool Group. If you are not an existing member you can learn how to become one on our [About](../about-koinonia-faq/) page.', 1, 'p')
on conflict (page, block_key) do update set original = excluded.original,
  sort_order = excluded.sort_order, tag = excluded.tag;
insert into public.site_content (page, block_key, original, sort_order, tag) values
  ('class-proposal-form/index.html', '2', 'Classes must meet at least one of these general requirements to be offered at Koinonia.', 2, 'p')
on conflict (page, block_key) do update set original = excluded.original,
  sort_order = excluded.sort_order, tag = excluded.tag;
insert into public.site_content (page, block_key, original, sort_order, tag) values
  ('class-proposal-form/index.html', '3', 'The class includes minimal homework', 3, 'li')
on conflict (page, block_key) do update set original = excluded.original,
  sort_order = excluded.sort_order, tag = excluded.tag;
insert into public.site_content (page, block_key, original, sort_order, tag) values
  ('class-proposal-form/index.html', '4', 'The class is an elective / enrichment based class, not a core subject class', 4, 'li')
on conflict (page, block_key) do update set original = excluded.original,
  sort_order = excluded.sort_order, tag = excluded.tag;
insert into public.site_content (page, block_key, original, sort_order, tag) values
  ('class-proposal-form/index.html', '5', 'The class is best accomplished in a group (choir, theater, sports, etc.)', 5, 'li')
on conflict (page, block_key) do update set original = excluded.original,
  sort_order = excluded.sort_order, tag = excluded.tag;
insert into public.site_content (page, block_key, original, sort_order, tag) values
  ('class-proposal-form/index.html', '6', 'The class teaches a skill that many parents may not be able to, or knowledgeable enough to teach at home.', 6, 'li')
on conflict (page, block_key) do update set original = excluded.original,
  sort_order = excluded.sort_order, tag = excluded.tag;
insert into public.site_content (page, block_key, original, sort_order, tag) values
  ('class-proposal-form/index.html', '7', 'We have found that the most successful classes are interactive and “hands-on.”', 7, 'p')
on conflict (page, block_key) do update set original = excluded.original,
  sort_order = excluded.sort_order, tag = excluded.tag;
insert into public.site_content (page, block_key, original, sort_order, tag) values
  ('class-proposal-form/index.html', '8', '[← Back](../class-proposal-form/)', 8, 'p')
on conflict (page, block_key) do update set original = excluded.original,
  sort_order = excluded.sort_order, tag = excluded.tag;
insert into public.site_content (page, block_key, original, sort_order, tag) values
  ('class-proposal-form/index.html', '9', 'Your proposal has been sent', 9, 'h4')
on conflict (page, block_key) do update set original = excluded.original,
  sort_order = excluded.sort_order, tag = excluded.tag;
insert into public.site_content (page, block_key, original, sort_order, tag) values
  ('class-proposal-form/index.html', '10', '[](context.item.anchor)', 10, 'li')
on conflict (page, block_key) do update set original = excluded.original,
  sort_order = excluded.sort_order, tag = excluded.tag;
insert into public.site_content (page, block_key, original, sort_order, tag) values
  ('class-proposal-form/index.html', '11', '*Classes with younger students require a helper. Older student classes are as needed.', 11, 'p')
on conflict (page, block_key) do update set original = excluded.original,
  sort_order = excluded.sort_order, tag = excluded.tag;
insert into public.site_content (page, block_key, original, sort_order, tag) values
  ('student-class-proposal-form/index.html', '1', 'This form is for students that are existing members of Koinonia Homeschool Group. If you are not an existing member you can learn how to become one on our [About](../about-koinonia-faq/) page.', 1, 'p')
on conflict (page, block_key) do update set original = excluded.original,
  sort_order = excluded.sort_order, tag = excluded.tag;
insert into public.site_content (page, block_key, original, sort_order, tag) values
  ('student-class-proposal-form/index.html', '2', 'Classes must meet at least one of these general requirements to be offered at Koinonia.', 2, 'p')
on conflict (page, block_key) do update set original = excluded.original,
  sort_order = excluded.sort_order, tag = excluded.tag;
insert into public.site_content (page, block_key, original, sort_order, tag) values
  ('student-class-proposal-form/index.html', '3', 'The class includes minimal homework', 3, 'li')
on conflict (page, block_key) do update set original = excluded.original,
  sort_order = excluded.sort_order, tag = excluded.tag;
insert into public.site_content (page, block_key, original, sort_order, tag) values
  ('student-class-proposal-form/index.html', '4', 'The class is an elective / enrichment based class, not a core subject class', 4, 'li')
on conflict (page, block_key) do update set original = excluded.original,
  sort_order = excluded.sort_order, tag = excluded.tag;
insert into public.site_content (page, block_key, original, sort_order, tag) values
  ('student-class-proposal-form/index.html', '5', 'The class is best accomplished in a group (choir, theater, sports, etc.)', 5, 'li')
on conflict (page, block_key) do update set original = excluded.original,
  sort_order = excluded.sort_order, tag = excluded.tag;
insert into public.site_content (page, block_key, original, sort_order, tag) values
  ('student-class-proposal-form/index.html', '6', 'The class teaches a skill that many parents may not be able to, or knowledgeable enough to teach at home.', 6, 'li')
on conflict (page, block_key) do update set original = excluded.original,
  sort_order = excluded.sort_order, tag = excluded.tag;
insert into public.site_content (page, block_key, original, sort_order, tag) values
  ('student-class-proposal-form/index.html', '7', 'We have found that the most successful classes are interactive and “hands-on.”', 7, 'p')
on conflict (page, block_key) do update set original = excluded.original,
  sort_order = excluded.sort_order, tag = excluded.tag;
insert into public.site_content (page, block_key, original, sort_order, tag) values
  ('student-class-proposal-form/index.html', '8', '[← Back](../student-class-proposal-form/)', 8, 'p')
on conflict (page, block_key) do update set original = excluded.original,
  sort_order = excluded.sort_order, tag = excluded.tag;
insert into public.site_content (page, block_key, original, sort_order, tag) values
  ('student-class-proposal-form/index.html', '9', 'Your proposal has been sent', 9, 'h4')
on conflict (page, block_key) do update set original = excluded.original,
  sort_order = excluded.sort_order, tag = excluded.tag;
insert into public.site_content (page, block_key, original, sort_order, tag) values
  ('student-class-proposal-form/index.html', '10', '[](context.item.anchor)', 10, 'li')
on conflict (page, block_key) do update set original = excluded.original,
  sort_order = excluded.sort_order, tag = excluded.tag;
insert into public.site_content (page, block_key, original, sort_order, tag) values
  ('class-description-form/index.html', '1', 'This form is for families that are existing members of Koinonia Homeschool Group. If you are not an existing member you can learn how to become one on our [About](../about-koinonia-faq/) page.', 1, 'p')
on conflict (page, block_key) do update set original = excluded.original,
  sort_order = excluded.sort_order, tag = excluded.tag;
insert into public.site_content (page, block_key, original, sort_order, tag) values
  ('class-description-form/index.html', '2', '[← Back](../class-description-form/)', 2, 'p')
on conflict (page, block_key) do update set original = excluded.original,
  sort_order = excluded.sort_order, tag = excluded.tag;
insert into public.site_content (page, block_key, original, sort_order, tag) values
  ('class-description-form/index.html', '3', 'Your proposal has been sent', 3, 'h4')
on conflict (page, block_key) do update set original = excluded.original,
  sort_order = excluded.sort_order, tag = excluded.tag;
insert into public.site_content (page, block_key, original, sort_order, tag) values
  ('class-description-form/index.html', '4', '[](context.item.anchor)', 4, 'li')
on conflict (page, block_key) do update set original = excluded.original,
  sort_order = excluded.sort_order, tag = excluded.tag;
insert into public.site_content (page, block_key, original, sort_order, tag) values
  ('fieldtrip-suggestion-form/index.html', '1', 'This form is for families that are existing members of Koinonia Homeschool Group. If you are not an existing member you can learn how to become one on our [About](../about-koinonia-faq/) page.', 1, 'p')
on conflict (page, block_key) do update set original = excluded.original,
  sort_order = excluded.sort_order, tag = excluded.tag;
insert into public.site_content (page, block_key, original, sort_order, tag) values
  ('fieldtrip-suggestion-form/index.html', '2', '[← Back](../fieldtrip-suggestion-form/)', 2, 'p')
on conflict (page, block_key) do update set original = excluded.original,
  sort_order = excluded.sort_order, tag = excluded.tag;
insert into public.site_content (page, block_key, original, sort_order, tag) values
  ('fieldtrip-suggestion-form/index.html', '3', 'Thank you for your fieldtrip suggestion!', 3, 'h4')
on conflict (page, block_key) do update set original = excluded.original,
  sort_order = excluded.sort_order, tag = excluded.tag;
insert into public.site_content (page, block_key, original, sort_order, tag) values
  ('fieldtrip-suggestion-form/index.html', '4', '[](context.item.anchor)', 4, 'li')
on conflict (page, block_key) do update set original = excluded.original,
  sort_order = excluded.sort_order, tag = excluded.tag;
insert into public.site_content (page, block_key, original, sort_order, tag) values
  ('apply/index.html', '1', '***2026-2027 Year is FULL***', 1, 'p')
on conflict (page, block_key) do update set original = excluded.original,
  sort_order = excluded.sort_order, tag = excluded.tag;
insert into public.site_content (page, block_key, original, sort_order, tag) values
  ('apply/index.html', '2', 'This form is the first step to joining our homeschool group. Applications must be approved before we will accept registrations. Expect us to be contacting you soon!', 2, 'p')
on conflict (page, block_key) do update set original = excluded.original,
  sort_order = excluded.sort_order, tag = excluded.tag;
