"""Builds the linerunner line banks from the Macbeth text in ../bard3/mac.html.

Writes data.js for Lady Macbeth (the page is index.html) and sean/data.js +
sean/index.html for Macbeth. sean/index.html is derived from index.html, so
edit index.html and re-run this; never edit sean/index.html by hand.

Each card = one speech by the character, with the lines spoken just before it (the
cue) and the speech (the answer). Run: python3 build_data.py
"""
import json, re, pathlib

here = pathlib.Path(__file__).parent
src = (here.parent / "bard3" / "mac.html").read_text()
data = json.loads(re.search(r"const DATA = (\{.*?\});\n", src, re.S).group(1))

def text(line):
    return "".join(t["t"] for t in line["toks"]).strip()

def speech_from(blocks, i):
    """All of the speaker's lines from blocks[i] until someone else speaks.

    A speech split by a stage direction (e.g. 'Knocking within.') continues;
    stage directions inside the speech are kept as {"s": ...} entries, and ones
    trailing after her last line are dropped.
    """
    who = blocks[i]["sp"]
    items, end = [], i
    for j in range(i, len(blocks)):
        b = blocks[j]
        if "stage" in b:
            items.append({"s": b["stage"]})
        elif b["sp"] == who:
            items += [{"l": text(l)} for l in b["lines"]]
            end = j
        else:
            break
    while items and "s" in items[-1]:
        items.pop()
    return items, end

def build(character):
    cards = []
    for scene in data["scenes"]:
        if scene["act"] == "cast":
            continue
        blocks = scene["blocks"]
        speeches = [(i, b) for i, b in enumerate(blocks) if b.get("sp")]
        skip_until = -1
        for k, (i, sp) in enumerate(speeches):
            if i <= skip_until or sp["sp"] != character or k == 0:
                continue
            prev = speeches[k - 1][1]
            if prev["sp"] == character:
                continue
            speech, end = speech_from(blocks, i)
            skip_until = end
            cue = [text(l) for l in prev["lines"]][-3:]
            first = text(sp["lines"][0])
            word = re.match(r"[^\w']*([\w']+)", first)
            if not cue or not word:
                continue
            cards.append({
                "act": scene["act"], "sc": scene["sc"], "n": sp["lines"][0]["n"],
                "who": prev["sp"], "cue": cue, "speech": speech, "word": word.group(1),
            })
    return cards


def write(path, cards):
    out = ("// Generated by build_data.py from the Macbeth text in ../bard3/mac.html\n"
           "window.LINES = " + json.dumps(cards, ensure_ascii=False, indent=1) + ";\n")
    path.write_text(out)
    print(path.relative_to(here), len(cards), "cards")


write(here / "data.js", build("Lady Macbeth"))

sean = here / "sean"
sean.mkdir(exist_ok=True)
write(sean / "data.js", build("Macbeth"))

page = (here / "index.html").read_text()
for old, new in [
    ("Lady Macbeth's", "Macbeth's"),
    ("Lady Macbeth", "Macbeth"),
    ('href="../', 'href="../../'),
    ("word of her reply", "word of his reply"),
]:
    page = page.replace(old, new)
(sean / "index.html").write_text(page)
print("sean/index.html written")
