"""Builds the linerunner line banks from the Macbeth text in ../bard3/mac.html.

Writes data.js for Lady Macbeth (the page is index.html) and sean/data.js +
sean/index.html for Macbeth. sean/index.html is derived from index.html, so
edit index.html and re-run this; never edit sean/index.html by hand.

Lines are stored as word tokens carrying their lexicon key, so the page can gloss
them against Schmidt's Lexicon the way bard3/mac.html does. The entries those
words need go to vocab.js, shared by both pages and loaded on the first tap.

Each card = one speech by the character, with the lines spoken just before it (the
cue) and the speech (the answer). Run: python3 build_data.py
"""
import json, re, pathlib

here = pathlib.Path(__file__).parent
src = (here.parent / "bard3" / "mac.html").read_text()
data = json.loads(re.search(r"const DATA = (\{.*?\});\n", src, re.S).group(1))

def text(line):
    return "".join(t["t"] for t in line["toks"]).strip()

GLOSS = ("k", "h", "d", "p", "x", "f", "g")

def toks(line):
    """Plain text stays a bare string; glossed words keep their lexicon fields."""
    out = []
    for t in line["toks"]:
        extra = {k: t[k] for k in GLOSS if k in t}
        out.append({"t": t["t"], **extra} if extra else t["t"])
    return out

def speech_from(blocks, i):
    """All of the speaker's lines from blocks[i] until someone else speaks.

    A speech split by a stage direction (e.g. 'Knocking within.') continues;
    stage directions inside the speech are kept as {"s": ...} entries, and ones
    trailing after her last line are dropped.
    """
    who = blocks[i]["sp"]
    items, end = [], i
    for j in range(i, len(blocks)):
        b = blocks[j]
        if "stage" in b:
            items.append({"s": b["stage"]})
        elif b["sp"] == who:
            items += [{"l": toks(l)} for l in b["lines"]]
            end = j
        else:
            break
    while items and "s" in items[-1]:
        items.pop()
    return items, end

def build(character):
    cards = []
    for scene in data["scenes"]:
        if scene["act"] == "cast":
            continue
        blocks = scene["blocks"]
        speeches = [(i, b) for i, b in enumerate(blocks) if b.get("sp")]
        skip_until = -1
        for k, (i, sp) in enumerate(speeches):
            if i <= skip_until or sp["sp"] != character:
                continue
            speech, end = speech_from(blocks, i)
            skip_until = end
            first = text(sp["lines"][0])
            word = re.match(r"[^\w']*([\w']+)", first)
            card = {"act": scene["act"], "sc": scene["sc"], "n": sp["lines"][0]["n"]}
            if k == 0:
                # Opens the scene, so nobody speaks before it: cue with where we are
                # and what the stage direction says (e.g. "Enter Lady Macbeth,
                # reading a letter.").
                card.update(who="", cue=[], opener={
                    "setting": scene["setting"],
                    "stage": " ".join(b["stage"] for b in blocks[:i] if "stage" in b),
                })
            else:
                prev = speeches[k - 1][1]
                if prev["sp"] == character:
                    continue
                card.update(who=prev["sp"], cue=[toks(l) for l in prev["lines"]][-3:])
            if not word or not (card["cue"] or card.get("opener")):
                continue
            card.update(speech=speech, word=word.group(1))
            cards.append(card)
    return cards


def write(path, cards):
    rows = ",\n".join(json.dumps(c, ensure_ascii=False, separators=(",", ":")) for c in cards)
    path.write_text("// Generated by build_data.py from the Macbeth text in ../bard3/mac.html\n"
                    "window.LINES = [\n" + rows + "\n];\n")
    print(path.relative_to(here), len(cards), "cards")


def keys_used(cards):
    found = set()
    def walk(line):
        found.update(t["k"] for t in line if isinstance(t, dict) and "k" in t)
    for c in cards:
        for line in c["cue"]:
            walk(line)
        for item in c["speech"]:
            if "l" in item:
                walk(item["l"])
    return found


lady, macbeth = build("Lady Macbeth"), build("Macbeth")
write(here / "data.js", lady)
sean = here / "sean"
sean.mkdir(exist_ok=True)
write(sean / "data.js", macbeth)

# Schmidt entries for every word either page can show, plus the sibling entries
# ("alts") the panel offers for homographs.
vocab = data["vocab"]
need = keys_used(lady) | keys_used(macbeth)
need |= {a for k in list(need) for a in vocab[k].get("alts", [])}
(here / "vocab.js").write_text(
    "// Generated by build_data.py: Schmidt's Shakespeare Lexicon (1902), the entries used by linerunner.\n"
    "window.VOCAB = " + json.dumps({k: vocab[k] for k in sorted(need) if k in vocab},
                                   ensure_ascii=False, separators=(",", ":")) + ";\n")
print("vocab.js", len(need), "entries")

page = (here / "index.html").read_text()
for old, new in [
    ("Lady Macbeth's", "Macbeth's"),
    ("Lady Macbeth", "Macbeth"),
    ('href="../', 'href="../../'),
    ('"vocab.js"', '"../vocab.js"'),
    ("word of her reply", "word of his reply"),
]:
    assert old in page, old
    page = page.replace(old, new)
(sean / "index.html").write_text(page)
print("sean/index.html written")
