// Generated by build_data.py from the Macbeth text in ../bard3/mac.html
window.LINES = [
 {
  "act": "1",
  "sc": "5",
  "n": 33,
  "who": "Messenger",
  "cue": [
   "The King comes here tonight."
  ],
  "line": "Thou'rt mad to say it.",
  "word": "Thou'rt"
 },
 {
  "act": "1",
  "sc": "5",
  "n": 38,
  "who": "Messenger",
  "cue": [
   "One of my fellows had the speed of him,",
   "Who, almost dead for breath, had scarcely more",
   "Than would make up his message."
  ],
  "line": "Give him tending.",
  "word": "Give"
 },
 {
  "act": "1",
  "sc": "5",
  "n": 60,
  "who": "Macbeth",
  "cue": [
   "My dearest love,",
   "Duncan comes here tonight."
  ],
  "line": "And when goes hence?",
  "word": "And"
 },
 {
  "act": "1",
  "sc": "5",
  "n": 62,
  "who": "Macbeth",
  "cue": [
   "Tomorrow, as he purposes."
  ],
  "line": "O, never",
  "word": "O"
 },
 {
  "act": "1",
  "sc": "5",
  "n": 73,
  "who": "Macbeth",
  "cue": [
   "We will speak further."
  ],
  "line": "Only look up clear;",
  "word": "Only"
 },
 {
  "act": "1",
  "sc": "6",
  "n": 14,
  "who": "Duncan",
  "cue": [
   "Which still we thank as love. Herein I teach you",
   "How you shall bid God 'ild us for your pains,",
   "And thank us for your trouble."
  ],
  "line": "All our service,",
  "word": "All"
 },
 {
  "act": "1",
  "sc": "6",
  "n": 25,
  "who": "Duncan",
  "cue": [
   "And his great love, sharp as his spur, hath holp him",
   "To his home before us. Fair and noble hostess,",
   "We are your guest tonight."
  ],
  "line": "Your servants ever",
  "word": "Your"
 },
 {
  "act": "1",
  "sc": "7",
  "n": 28,
  "who": "Macbeth",
  "cue": [
   "How now! what news?"
  ],
  "line": "He has almost supp'd. Why have you left the chamber?",
  "word": "He"
 },
 {
  "act": "1",
  "sc": "7",
  "n": 30,
  "who": "Macbeth",
  "cue": [
   "Hath he ask'd for me?"
  ],
  "line": "Know you not he has?",
  "word": "Know"
 },
 {
  "act": "1",
  "sc": "7",
  "n": 35,
  "who": "Macbeth",
  "cue": [
   "Golden opinions from all sorts of people,",
   "Which would be worn now in their newest gloss,",
   "Not cast aside so soon."
  ],
  "line": "Was the hope drunk",
  "word": "Was"
 },
 {
  "act": "1",
  "sc": "7",
  "n": 48,
  "who": "Macbeth",
  "cue": [
   "Pr'ythee, peace!",
   "I dare do all that may become a man;",
   "Who dares do more is none."
  ],
  "line": "What beast was't, then,",
  "word": "What"
 },
 {
  "act": "1",
  "sc": "7",
  "n": 59,
  "who": "Macbeth",
  "cue": [
   "If we should fail?"
  ],
  "line": "We fail?",
  "word": "We"
 },
 {
  "act": "1",
  "sc": "7",
  "n": 77,
  "who": "Macbeth",
  "cue": [
   "When we have mark'd with blood those sleepy two",
   "Of his own chamber, and us'd their very daggers,",
   "That they have done't?"
  ],
  "line": "Who dares receive it other,",
  "word": "Who"
 },
 {
  "act": "2",
  "sc": "2",
  "n": 12,
  "who": "Macbeth",
  "cue": [
   "I have done the deed.--Didst thou not hear a noise?"
  ],
  "line": "I heard the owl scream and the crickets cry.",
  "word": "I"
 },
 {
  "act": "2",
  "sc": "2",
  "n": 16,
  "who": "Macbeth",
  "cue": [
   "When?"
  ],
  "line": "Now.",
  "word": "Now"
 },
 {
  "act": "2",
  "sc": "2",
  "n": 18,
  "who": "Macbeth",
  "cue": [
   "As I descended?"
  ],
  "line": "Ay.",
  "word": "Ay"
 },
 {
  "act": "2",
  "sc": "2",
  "n": 20,
  "who": "Macbeth",
  "cue": [
   "Hark!--Who lies i' th' second chamber?"
  ],
  "line": "Donalbain.",
  "word": "Donalbain"
 },
 {
  "act": "2",
  "sc": "2",
  "n": 22,
  "who": "Macbeth",
  "cue": [
   "This is a sorry sight."
  ],
  "line": "A foolish thought, to say a sorry sight.",
  "word": "A"
 },
 {
  "act": "2",
  "sc": "2",
  "n": 26,
  "who": "Macbeth",
  "cue": [
   "That they did wake each other: I stood and heard them.",
   "But they did say their prayers, and address'd them",
   "Again to sleep."
  ],
  "line": "There are two lodg'd together.",
  "word": "There"
 },
 {
  "act": "2",
  "sc": "2",
  "n": 30,
  "who": "Macbeth",
  "cue": [
   "As they had seen me with these hangman's hands.",
   "List'ning their fear, I could not say \"Amen,\"",
   "When they did say, \"God bless us.\""
  ],
  "line": "Consider it not so deeply.",
  "word": "Consider"
 },
 {
  "act": "2",
  "sc": "2",
  "n": 33,
  "who": "Macbeth",
  "cue": [
   "But wherefore could not I pronounce \"Amen\"?",
   "I had most need of blessing, and \"Amen\"",
   "Stuck in my throat."
  ],
  "line": "These deeds must not be thought",
  "word": "These"
 },
 {
  "act": "2",
  "sc": "2",
  "n": 39,
  "who": "Macbeth",
  "cue": [
   "The death of each day's life, sore labour's bath,",
   "Balm of hurt minds, great nature's second course,",
   "Chief nourisher in life's feast."
  ],
  "line": "What do you mean?",
  "word": "What"
 },
 {
  "act": "2",
  "sc": "2",
  "n": 43,
  "who": "Macbeth",
  "cue": [
   "Still it cried, \"Sleep no more!\" to all the house:",
   "\"Glamis hath murder'd sleep, and therefore Cawdor",
   "Shall sleep no more. Macbeth shall sleep no more!\""
  ],
  "line": "Who was it that thus cried? Why, worthy thane,",
  "word": "Who"
 },
 {
  "act": "2",
  "sc": "2",
  "n": 53,
  "who": "Macbeth",
  "cue": [
   "I'll go no more:",
   "I am afraid to think what I have done;",
   "Look on't again I dare not."
  ],
  "line": "Infirm of purpose!",
  "word": "Infirm"
 },
 {
  "act": "2",
  "sc": "2",
  "n": 65,
  "who": "Macbeth",
  "cue": [
   "Clean from my hand? No, this my hand will rather",
   "The multitudinous seas incarnadine,",
   "Making the green one red."
  ],
  "line": "My hands are of your color, but I shame",
  "word": "My"
 },
 {
  "act": "2",
  "sc": "3",
  "n": 85,
  "who": "Macduff",
  "cue": [
   "The great doom's image. Malcolm! Banquo!",
   "As from your graves rise up, and walk like sprites",
   "To countenance this horror!"
  ],
  "line": "What's the business,",
  "word": "What's"
 },
 {
  "act": "2",
  "sc": "3",
  "n": 93,
  "who": "Macduff",
  "cue": [
   "O Banquo, Banquo!",
   "Our royal master's murder'd!"
  ],
  "line": "Woe, alas!",
  "word": "Woe"
 },
 {
  "act": "2",
  "sc": "3",
  "n": 124,
  "who": "Macbeth",
  "cue": [
   "Unmannerly breech'd with gore. Who could refrain,",
   "That had a heart to love, and in that heart",
   "Courage to make's love known?"
  ],
  "line": "Help me hence, ho!",
  "word": "Help"
 },
 {
  "act": "3",
  "sc": "1",
  "n": 11,
  "who": "Macbeth",
  "cue": [
   "Here's our chief guest."
  ],
  "line": "If he had been forgotten,",
  "word": "If"
 },
 {
  "act": "3",
  "sc": "2",
  "n": 3,
  "who": "Servant",
  "cue": [
   "Ay, madam, but returns again tonight."
  ],
  "line": "Say to the King, I would attend his leisure",
  "word": "Say"
 },
 {
  "act": "3",
  "sc": "2",
  "n": 5,
  "who": "Servant",
  "cue": [
   "Madam, I will."
  ],
  "line": "Naught's had, all's spent,",
  "word": "Naught's"
 },
 {
  "act": "3",
  "sc": "2",
  "n": 26,
  "who": "Macbeth",
  "cue": [
   "Treason has done his worst: nor steel, nor poison,",
   "Malice domestic, foreign levy, nothing",
   "Can touch him further."
  ],
  "line": "Come on,",
  "word": "Come"
 },
 {
  "act": "3",
  "sc": "2",
  "n": 35,
  "who": "Macbeth",
  "cue": [
   "Must lave our honours in these flattering streams,",
   "And make our faces vizards to our hearts,",
   "Disguising what they are."
  ],
  "line": "You must leave this.",
  "word": "You"
 },
 {
  "act": "3",
  "sc": "2",
  "n": 38,
  "who": "Macbeth",
  "cue": [
   "O, full of scorpions is my mind, dear wife!",
   "Thou know'st that Banquo, and his Fleance, lives."
  ],
  "line": "But in them nature's copy's not eterne.",
  "word": "But"
 },
 {
  "act": "3",
  "sc": "2",
  "n": 45,
  "who": "Macbeth",
  "cue": [
   "The shard-born beetle, with his drowsy hums,",
   "Hath rung night's yawning peal, there shall be done",
   "A deed of dreadful note."
  ],
  "line": "What's to be done?",
  "word": "What's"
 },
 {
  "act": "3",
  "sc": "4",
  "n": 7,
  "who": "Macbeth",
  "cue": [
   "And play the humble host.",
   "Our hostess keeps her state; but, in best time,",
   "We will require her welcome."
  ],
  "line": "Pronounce it for me, sir, to all our friends;",
  "word": "Pronounce"
 },
 {
  "act": "3",
  "sc": "4",
  "n": 32,
  "who": "Macbeth",
  "cue": [
   "Hath nature that in time will venom breed,",
   "No teeth for th' present.--Get thee gone; tomorrow",
   "We'll hear, ourselves, again."
  ],
  "line": "My royal lord,",
  "word": "My"
 },
 {
  "act": "3",
  "sc": "4",
  "n": 53,
  "who": "Ross",
  "cue": [
   "Gentlemen, rise; his Highness is not well."
  ],
  "line": "Sit, worthy friends. My lord is often thus,",
  "word": "Sit"
 },
 {
  "act": "3",
  "sc": "4",
  "n": 60,
  "who": "Macbeth",
  "cue": [
   "Ay, and a bold one, that dare look on that",
   "Which might appal the devil."
  ],
  "line": "O proper stuff!",
  "word": "O"
 },
 {
  "act": "3",
  "sc": "4",
  "n": 73,
  "who": "Macbeth",
  "cue": [
   "If charnel houses and our graves must send",
   "Those that we bury back, our monuments",
   "Shall be the maws of kites."
  ],
  "line": "What, quite unmann'd in folly?",
  "word": "What"
 },
 {
  "act": "3",
  "sc": "4",
  "n": 75,
  "who": "Macbeth",
  "cue": [
   "If I stand here, I saw him."
  ],
  "line": "Fie, for shame!",
  "word": "Fie"
 },
 {
  "act": "3",
  "sc": "4",
  "n": 84,
  "who": "Macbeth",
  "cue": [
   "With twenty mortal murders on their crowns,",
   "And push us from our stools. This is more strange",
   "Than such a murder is."
  ],
  "line": "My worthy lord,",
  "word": "My"
 },
 {
  "act": "3",
  "sc": "4",
  "n": 98,
  "who": "Macbeth",
  "cue": [
   "Thy bones are marrowless, thy blood is cold;",
   "Thou hast no speculation in those eyes",
   "Which thou dost glare with!"
  ],
  "line": "Think of this, good peers,",
  "word": "Think"
 },
 {
  "act": "3",
  "sc": "4",
  "n": 108,
  "who": "Macbeth",
  "cue": [
   "Why, so;--being gone,",
   "I am a man again.--Pray you, sit still."
  ],
  "line": "You have displaced the mirth, broke the good meeting",
  "word": "You"
 },
 {
  "act": "3",
  "sc": "4",
  "n": 117,
  "who": "Ross",
  "cue": [
   "What sights, my lord?"
  ],
  "line": "I pray you, speak not; he grows worse and worse;",
  "word": "I"
 },
 {
  "act": "3",
  "sc": "4",
  "n": 122,
  "who": "Lennox",
  "cue": [
   "Good night; and better health",
   "Attend his Majesty!"
  ],
  "line": "A kind good night to all!",
  "word": "A"
 },
 {
  "act": "3",
  "sc": "4",
  "n": 126,
  "who": "Macbeth",
  "cue": [
   "Augurs, and understood relations, have",
   "By magot-pies, and choughs, and rooks, brought forth",
   "The secret'st man of blood.--What is the night?"
  ],
  "line": "Almost at odds with morning, which is which.",
  "word": "Almost"
 },
 {
  "act": "3",
  "sc": "4",
  "n": 128,
  "who": "Macbeth",
  "cue": [
   "How say'st thou, that Macduff denies his person",
   "At our great bidding?"
  ],
  "line": "Did you send to him, sir?",
  "word": "Did"
 },
 {
  "act": "3",
  "sc": "4",
  "n": 140,
  "who": "Macbeth",
  "cue": [
   "Returning were as tedious as go o'er.",
   "Strange things I have in head, that will to hand,",
   "Which must be acted ere they may be scann'd."
  ],
  "line": "You lack the season of all natures, sleep.",
  "word": "You"
 },
 {
  "act": "5",
  "sc": "1",
  "n": 35,
  "who": "Gentlewoman",
  "cue": [
   "It is an accustomed action with her, to seem thus washing her hands. I",
   "have known her continue in this a quarter of an hour."
  ],
  "line": "Yet here's a spot.",
  "word": "Yet"
 },
 {
  "act": "5",
  "sc": "1",
  "n": 39,
  "who": "Doctor",
  "cue": [
   "Hark, she speaks. I will set down what comes from her, to satisfy my",
   "remembrance the more strongly."
  ],
  "line": "Out, damned spot! out, I say! One; two. Why, then 'tis time to do't.",
  "word": "Out"
 },
 {
  "act": "5",
  "sc": "1",
  "n": 47,
  "who": "Doctor",
  "cue": [
   "Do you mark that?"
  ],
  "line": "The Thane of Fife had a wife. Where is she now?--What, will these hands",
  "word": "The"
 },
 {
  "act": "5",
  "sc": "1",
  "n": 57,
  "who": "Gentlewoman",
  "cue": [
   "She has spoke what she should not, I am sure of that: heaven knows what",
   "she has known."
  ],
  "line": "Here's the smell of the blood still: all the perfumes of Arabia will",
  "word": "Here's"
 },
 {
  "act": "5",
  "sc": "1",
  "n": 66,
  "who": "Doctor",
  "cue": [
   "This disease is beyond my practice: yet I have known those which have",
   "walked in their sleep, who have died holily in their beds."
  ],
  "line": "Wash your hands, put on your nightgown; look not so pale. I tell you",
  "word": "Wash"
 },
 {
  "act": "5",
  "sc": "1",
  "n": 69,
  "who": "Doctor",
  "cue": [
   "Even so?"
  ],
  "line": "To bed, to bed. There's knocking at the gate. Come, come, come, come,",
  "word": "To"
 }
];
