// Generated by build_data.py from the Macbeth text in ../bard3/mac.html
window.LINES = [
 {
  "act": "1",
  "sc": "5",
  "n": 33,
  "who": "Messenger",
  "cue": [
   "The King comes here tonight."
  ],
  "speech": [
   {
    "l": "Thou'rt mad to say it."
   },
   {
    "l": "Is not thy master with him? who, were't so,"
   },
   {
    "l": "Would have inform'd for preparation."
   }
  ],
  "word": "Thou'rt"
 },
 {
  "act": "1",
  "sc": "5",
  "n": 38,
  "who": "Messenger",
  "cue": [
   "One of my fellows had the speed of him,",
   "Who, almost dead for breath, had scarcely more",
   "Than would make up his message."
  ],
  "speech": [
   {
    "l": "Give him tending."
   },
   {
    "l": "He brings great news."
   },
   {
    "s": "Exit Messenger."
   },
   {
    "l": "The raven himself is hoarse"
   },
   {
    "l": "That croaks the fatal entrance of Duncan"
   },
   {
    "l": "Under my battlements. Come, you spirits"
   },
   {
    "l": "That tend on mortal thoughts, unsex me here,"
   },
   {
    "l": "And fill me, from the crown to the toe, top-full"
   },
   {
    "l": "Of direst cruelty! make thick my blood,"
   },
   {
    "l": "Stop up th' access and passage to remorse,"
   },
   {
    "l": "That no compunctious visitings of nature"
   },
   {
    "l": "Shake my fell purpose, nor keep peace between"
   },
   {
    "l": "Th' effect and it! Come to my woman's breasts,"
   },
   {
    "l": "And take my milk for gall, your murd'ring ministers,"
   },
   {
    "l": "Wherever in your sightless substances"
   },
   {
    "l": "You wait on nature's mischief! Come, thick night,"
   },
   {
    "l": "And pall thee in the dunnest smoke of hell"
   },
   {
    "l": "That my keen knife see not the wound it makes,"
   },
   {
    "l": "Nor heaven peep through the blanket of the dark"
   },
   {
    "l": "To cry, \"Hold, hold!\""
   },
   {
    "s": "Enter Macbeth."
   },
   {
    "l": "Great Glamis, worthy Cawdor!"
   },
   {
    "l": "Greater than both, by the all-hail hereafter!"
   },
   {
    "l": "Thy letters have transported me beyond"
   },
   {
    "l": "This ignorant present, and I feel now"
   },
   {
    "l": "The future in the instant."
   }
  ],
  "word": "Give"
 },
 {
  "act": "1",
  "sc": "5",
  "n": 60,
  "who": "Macbeth",
  "cue": [
   "My dearest love,",
   "Duncan comes here tonight."
  ],
  "speech": [
   {
    "l": "And when goes hence?"
   }
  ],
  "word": "And"
 },
 {
  "act": "1",
  "sc": "5",
  "n": 62,
  "who": "Macbeth",
  "cue": [
   "Tomorrow, as he purposes."
  ],
  "speech": [
   {
    "l": "O, never"
   },
   {
    "l": "Shall sun that morrow see!"
   },
   {
    "l": "Your face, my thane, is as a book where men"
   },
   {
    "l": "May read strange matters. To beguile the time,"
   },
   {
    "l": "Look like the time; bear welcome in your eye,"
   },
   {
    "l": "Your hand, your tongue: look like the innocent flower,"
   },
   {
    "l": "But be the serpent under't. He that's coming"
   },
   {
    "l": "Must be provided for; and you shall put"
   },
   {
    "l": "This night's great business into my dispatch;"
   },
   {
    "l": "Which shall to all our nights and days to come"
   },
   {
    "l": "Give solely sovereign sway and masterdom."
   }
  ],
  "word": "O"
 },
 {
  "act": "1",
  "sc": "5",
  "n": 73,
  "who": "Macbeth",
  "cue": [
   "We will speak further."
  ],
  "speech": [
   {
    "l": "Only look up clear;"
   },
   {
    "l": "To alter favour ever is to fear."
   },
   {
    "l": "Leave all the rest to me."
   }
  ],
  "word": "Only"
 },
 {
  "act": "1",
  "sc": "6",
  "n": 14,
  "who": "Duncan",
  "cue": [
   "Which still we thank as love. Herein I teach you",
   "How you shall bid God 'ild us for your pains,",
   "And thank us for your trouble."
  ],
  "speech": [
   {
    "l": "All our service,"
   },
   {
    "l": "In every point twice done, and then done double,"
   },
   {
    "l": "Were poor and single business to contend"
   },
   {
    "l": "Against those honours deep and broad wherewith"
   },
   {
    "l": "Your Majesty loads our house: for those of old,"
   },
   {
    "l": "And the late dignities heap'd up to them,"
   },
   {
    "l": "We rest your hermits."
   }
  ],
  "word": "All"
 },
 {
  "act": "1",
  "sc": "6",
  "n": 25,
  "who": "Duncan",
  "cue": [
   "And his great love, sharp as his spur, hath holp him",
   "To his home before us. Fair and noble hostess,",
   "We are your guest tonight."
  ],
  "speech": [
   {
    "l": "Your servants ever"
   },
   {
    "l": "Have theirs, themselves, and what is theirs, in compt,"
   },
   {
    "l": "To make their audit at your Highness' pleasure,"
   },
   {
    "l": "Still to return your own."
   }
  ],
  "word": "Your"
 },
 {
  "act": "1",
  "sc": "7",
  "n": 28,
  "who": "Macbeth",
  "cue": [
   "How now! what news?"
  ],
  "speech": [
   {
    "l": "He has almost supp'd. Why have you left the chamber?"
   }
  ],
  "word": "He"
 },
 {
  "act": "1",
  "sc": "7",
  "n": 30,
  "who": "Macbeth",
  "cue": [
   "Hath he ask'd for me?"
  ],
  "speech": [
   {
    "l": "Know you not he has?"
   }
  ],
  "word": "Know"
 },
 {
  "act": "1",
  "sc": "7",
  "n": 35,
  "who": "Macbeth",
  "cue": [
   "Golden opinions from all sorts of people,",
   "Which would be worn now in their newest gloss,",
   "Not cast aside so soon."
  ],
  "speech": [
   {
    "l": "Was the hope drunk"
   },
   {
    "l": "Wherein you dress'd yourself? Hath it slept since?"
   },
   {
    "l": "And wakes it now, to look so green and pale"
   },
   {
    "l": "At what it did so freely? From this time"
   },
   {
    "l": "Such I account thy love. Art thou afeard"
   },
   {
    "l": "To be the same in thine own act and valour"
   },
   {
    "l": "As thou art in desire? Wouldst thou have that"
   },
   {
    "l": "Which thou esteem'st the ornament of life,"
   },
   {
    "l": "And live a coward in thine own esteem,"
   },
   {
    "l": "Letting \"I dare not\" wait upon \"I would,\""
   },
   {
    "l": "Like the poor cat i' th' adage?"
   }
  ],
  "word": "Was"
 },
 {
  "act": "1",
  "sc": "7",
  "n": 48,
  "who": "Macbeth",
  "cue": [
   "Pr'ythee, peace!",
   "I dare do all that may become a man;",
   "Who dares do more is none."
  ],
  "speech": [
   {
    "l": "What beast was't, then,"
   },
   {
    "l": "That made you break this enterprise to me?"
   },
   {
    "l": "When you durst do it, then you were a man;"
   },
   {
    "l": "And, to be more than what you were, you would"
   },
   {
    "l": "Be so much more the man. Nor time nor place"
   },
   {
    "l": "Did then adhere, and yet you would make both:"
   },
   {
    "l": "They have made themselves, and that their fitness now"
   },
   {
    "l": "Does unmake you. I have given suck, and know"
   },
   {
    "l": "How tender 'tis to love the babe that milks me:"
   },
   {
    "l": "I would, while it was smiling in my face,"
   },
   {
    "l": "Have pluck'd my nipple from his boneless gums"
   },
   {
    "l": "And dash'd the brains out, had I so sworn as you"
   },
   {
    "l": "Have done to this."
   }
  ],
  "word": "What"
 },
 {
  "act": "1",
  "sc": "7",
  "n": 59,
  "who": "Macbeth",
  "cue": [
   "If we should fail?"
  ],
  "speech": [
   {
    "l": "We fail?"
   },
   {
    "l": "But screw your courage to the sticking-place,"
   },
   {
    "l": "And we'll not fail. When Duncan is asleep"
   },
   {
    "l": "(Whereto the rather shall his day's hard journey"
   },
   {
    "l": "Soundly invite him), his two chamberlains"
   },
   {
    "l": "Will I with wine and wassail so convince"
   },
   {
    "l": "That memory, the warder of the brain,"
   },
   {
    "l": "Shall be a fume, and the receipt of reason"
   },
   {
    "l": "A limbeck only: when in swinish sleep"
   },
   {
    "l": "Their drenched natures lie as in a death,"
   },
   {
    "l": "What cannot you and I perform upon"
   },
   {
    "l": "Th' unguarded Duncan? what not put upon"
   },
   {
    "l": "His spongy officers; who shall bear the guilt"
   },
   {
    "l": "Of our great quell?"
   }
  ],
  "word": "We"
 },
 {
  "act": "1",
  "sc": "7",
  "n": 77,
  "who": "Macbeth",
  "cue": [
   "When we have mark'd with blood those sleepy two",
   "Of his own chamber, and us'd their very daggers,",
   "That they have done't?"
  ],
  "speech": [
   {
    "l": "Who dares receive it other,"
   },
   {
    "l": "As we shall make our griefs and clamour roar"
   },
   {
    "l": "Upon his death?"
   }
  ],
  "word": "Who"
 },
 {
  "act": "2",
  "sc": "2",
  "n": 12,
  "who": "Macbeth",
  "cue": [
   "I have done the deed.--Didst thou not hear a noise?"
  ],
  "speech": [
   {
    "l": "I heard the owl scream and the crickets cry."
   },
   {
    "l": "Did not you speak?"
   }
  ],
  "word": "I"
 },
 {
  "act": "2",
  "sc": "2",
  "n": 16,
  "who": "Macbeth",
  "cue": [
   "When?"
  ],
  "speech": [
   {
    "l": "Now."
   }
  ],
  "word": "Now"
 },
 {
  "act": "2",
  "sc": "2",
  "n": 18,
  "who": "Macbeth",
  "cue": [
   "As I descended?"
  ],
  "speech": [
   {
    "l": "Ay."
   }
  ],
  "word": "Ay"
 },
 {
  "act": "2",
  "sc": "2",
  "n": 20,
  "who": "Macbeth",
  "cue": [
   "Hark!--Who lies i' th' second chamber?"
  ],
  "speech": [
   {
    "l": "Donalbain."
   }
  ],
  "word": "Donalbain"
 },
 {
  "act": "2",
  "sc": "2",
  "n": 22,
  "who": "Macbeth",
  "cue": [
   "This is a sorry sight."
  ],
  "speech": [
   {
    "l": "A foolish thought, to say a sorry sight."
   }
  ],
  "word": "A"
 },
 {
  "act": "2",
  "sc": "2",
  "n": 26,
  "who": "Macbeth",
  "cue": [
   "That they did wake each other: I stood and heard them.",
   "But they did say their prayers, and address'd them",
   "Again to sleep."
  ],
  "speech": [
   {
    "l": "There are two lodg'd together."
   }
  ],
  "word": "There"
 },
 {
  "act": "2",
  "sc": "2",
  "n": 30,
  "who": "Macbeth",
  "cue": [
   "As they had seen me with these hangman's hands.",
   "List'ning their fear, I could not say \"Amen,\"",
   "When they did say, \"God bless us.\""
  ],
  "speech": [
   {
    "l": "Consider it not so deeply."
   }
  ],
  "word": "Consider"
 },
 {
  "act": "2",
  "sc": "2",
  "n": 33,
  "who": "Macbeth",
  "cue": [
   "But wherefore could not I pronounce \"Amen\"?",
   "I had most need of blessing, and \"Amen\"",
   "Stuck in my throat."
  ],
  "speech": [
   {
    "l": "These deeds must not be thought"
   },
   {
    "l": "After these ways; so, it will make us mad."
   }
  ],
  "word": "These"
 },
 {
  "act": "2",
  "sc": "2",
  "n": 39,
  "who": "Macbeth",
  "cue": [
   "The death of each day's life, sore labour's bath,",
   "Balm of hurt minds, great nature's second course,",
   "Chief nourisher in life's feast."
  ],
  "speech": [
   {
    "l": "What do you mean?"
   }
  ],
  "word": "What"
 },
 {
  "act": "2",
  "sc": "2",
  "n": 43,
  "who": "Macbeth",
  "cue": [
   "Still it cried, \"Sleep no more!\" to all the house:",
   "\"Glamis hath murder'd sleep, and therefore Cawdor",
   "Shall sleep no more. Macbeth shall sleep no more!\""
  ],
  "speech": [
   {
    "l": "Who was it that thus cried? Why, worthy thane,"
   },
   {
    "l": "You do unbend your noble strength to think"
   },
   {
    "l": "So brainsickly of things. Go get some water,"
   },
   {
    "l": "And wash this filthy witness from your hand.--"
   },
   {
    "l": "Why did you bring these daggers from the place?"
   },
   {
    "l": "They must lie there: go carry them, and smear"
   },
   {
    "l": "The sleepy grooms with blood."
   }
  ],
  "word": "Who"
 },
 {
  "act": "2",
  "sc": "2",
  "n": 53,
  "who": "Macbeth",
  "cue": [
   "I'll go no more:",
   "I am afraid to think what I have done;",
   "Look on't again I dare not."
  ],
  "speech": [
   {
    "l": "Infirm of purpose!"
   },
   {
    "l": "Give me the daggers. The sleeping and the dead"
   },
   {
    "l": "Are but as pictures. 'Tis the eye of childhood"
   },
   {
    "l": "That fears a painted devil. If he do bleed,"
   },
   {
    "l": "I'll gild the faces of the grooms withal,"
   },
   {
    "l": "For it must seem their guilt."
   }
  ],
  "word": "Infirm"
 },
 {
  "act": "2",
  "sc": "2",
  "n": 65,
  "who": "Macbeth",
  "cue": [
   "Clean from my hand? No, this my hand will rather",
   "The multitudinous seas incarnadine,",
   "Making the green one red."
  ],
  "speech": [
   {
    "l": "My hands are of your color, but I shame"
   },
   {
    "s": "Knocking within."
   },
   {
    "l": "To wear a heart so white.   I hear knocking"
   },
   {
    "l": "At the south entry:--retire we to our chamber."
   },
   {
    "l": "A little water clears us of this deed:"
   },
   {
    "l": "How easy is it then! Your constancy"
   },
   {
    "s": "Knocking within."
   },
   {
    "l": "Hath left you unattended.--  Hark, more knocking."
   },
   {
    "l": "Get on your nightgown, lest occasion call us"
   },
   {
    "l": "And show us to be watchers. Be not lost"
   },
   {
    "l": "So poorly in your thoughts."
   }
  ],
  "word": "My"
 },
 {
  "act": "2",
  "sc": "3",
  "n": 85,
  "who": "Macduff",
  "cue": [
   "The great doom's image. Malcolm! Banquo!",
   "As from your graves rise up, and walk like sprites",
   "To countenance this horror!"
  ],
  "speech": [
   {
    "l": "What's the business,"
   },
   {
    "l": "That such a hideous trumpet calls to parley"
   },
   {
    "l": "The sleepers of the house? Speak, speak!"
   }
  ],
  "word": "What's"
 },
 {
  "act": "2",
  "sc": "3",
  "n": 93,
  "who": "Macduff",
  "cue": [
   "O Banquo, Banquo!",
   "Our royal master's murder'd!"
  ],
  "speech": [
   {
    "l": "Woe, alas!"
   },
   {
    "l": "What, in our house?"
   }
  ],
  "word": "Woe"
 },
 {
  "act": "2",
  "sc": "3",
  "n": 124,
  "who": "Macbeth",
  "cue": [
   "Unmannerly breech'd with gore. Who could refrain,",
   "That had a heart to love, and in that heart",
   "Courage to make's love known?"
  ],
  "speech": [
   {
    "l": "Help me hence, ho!"
   }
  ],
  "word": "Help"
 },
 {
  "act": "3",
  "sc": "1",
  "n": 11,
  "who": "Macbeth",
  "cue": [
   "Here's our chief guest."
  ],
  "speech": [
   {
    "l": "If he had been forgotten,"
   },
   {
    "l": "It had been as a gap in our great feast,"
   },
   {
    "l": "And all-thing unbecoming."
   }
  ],
  "word": "If"
 },
 {
  "act": "3",
  "sc": "2",
  "n": 3,
  "who": "Servant",
  "cue": [
   "Ay, madam, but returns again tonight."
  ],
  "speech": [
   {
    "l": "Say to the King, I would attend his leisure"
   },
   {
    "l": "For a few words."
   }
  ],
  "word": "Say"
 },
 {
  "act": "3",
  "sc": "2",
  "n": 5,
  "who": "Servant",
  "cue": [
   "Madam, I will."
  ],
  "speech": [
   {
    "l": "Naught's had, all's spent,"
   },
   {
    "l": "Where our desire is got without content:"
   },
   {
    "l": "'Tis safer to be that which we destroy,"
   },
   {
    "l": "Than by destruction dwell in doubtful joy."
   },
   {
    "s": "Enter Macbeth."
   },
   {
    "l": "How now, my lord, why do you keep alone,"
   },
   {
    "l": "Of sorriest fancies your companions making,"
   },
   {
    "l": "Using those thoughts which should indeed have died"
   },
   {
    "l": "With them they think on? Things without all remedy"
   },
   {
    "l": "Should be without regard: what's done is done."
   }
  ],
  "word": "Naught's"
 },
 {
  "act": "3",
  "sc": "2",
  "n": 26,
  "who": "Macbeth",
  "cue": [
   "Treason has done his worst: nor steel, nor poison,",
   "Malice domestic, foreign levy, nothing",
   "Can touch him further."
  ],
  "speech": [
   {
    "l": "Come on,"
   },
   {
    "l": "Gently my lord, sleek o'er your rugged looks;"
   },
   {
    "l": "Be bright and jovial among your guests tonight."
   }
  ],
  "word": "Come"
 },
 {
  "act": "3",
  "sc": "2",
  "n": 35,
  "who": "Macbeth",
  "cue": [
   "Must lave our honours in these flattering streams,",
   "And make our faces vizards to our hearts,",
   "Disguising what they are."
  ],
  "speech": [
   {
    "l": "You must leave this."
   }
  ],
  "word": "You"
 },
 {
  "act": "3",
  "sc": "2",
  "n": 38,
  "who": "Macbeth",
  "cue": [
   "O, full of scorpions is my mind, dear wife!",
   "Thou know'st that Banquo, and his Fleance, lives."
  ],
  "speech": [
   {
    "l": "But in them nature's copy's not eterne."
   }
  ],
  "word": "But"
 },
 {
  "act": "3",
  "sc": "2",
  "n": 45,
  "who": "Macbeth",
  "cue": [
   "The shard-born beetle, with his drowsy hums,",
   "Hath rung night's yawning peal, there shall be done",
   "A deed of dreadful note."
  ],
  "speech": [
   {
    "l": "What's to be done?"
   }
  ],
  "word": "What's"
 },
 {
  "act": "3",
  "sc": "4",
  "n": 7,
  "who": "Macbeth",
  "cue": [
   "And play the humble host.",
   "Our hostess keeps her state; but, in best time,",
   "We will require her welcome."
  ],
  "speech": [
   {
    "l": "Pronounce it for me, sir, to all our friends;"
   },
   {
    "l": "For my heart speaks they are welcome."
   }
  ],
  "word": "Pronounce"
 },
 {
  "act": "3",
  "sc": "4",
  "n": 32,
  "who": "Macbeth",
  "cue": [
   "Hath nature that in time will venom breed,",
   "No teeth for th' present.--Get thee gone; tomorrow",
   "We'll hear, ourselves, again."
  ],
  "speech": [
   {
    "l": "My royal lord,"
   },
   {
    "l": "You do not give the cheer: the feast is sold"
   },
   {
    "l": "That is not often vouch'd, while 'tis a-making,"
   },
   {
    "l": "'Tis given with welcome. To feed were best at home;"
   },
   {
    "l": "From thence the sauce to meat is ceremony;"
   },
   {
    "l": "Meeting were bare without it."
   }
  ],
  "word": "My"
 },
 {
  "act": "3",
  "sc": "4",
  "n": 53,
  "who": "Ross",
  "cue": [
   "Gentlemen, rise; his Highness is not well."
  ],
  "speech": [
   {
    "l": "Sit, worthy friends. My lord is often thus,"
   },
   {
    "l": "And hath been from his youth: pray you, keep seat;"
   },
   {
    "l": "The fit is momentary; upon a thought"
   },
   {
    "l": "He will again be well. If much you note him,"
   },
   {
    "l": "You shall offend him, and extend his passion."
   },
   {
    "l": "Feed, and regard him not.--Are you a man?"
   }
  ],
  "word": "Sit"
 },
 {
  "act": "3",
  "sc": "4",
  "n": 60,
  "who": "Macbeth",
  "cue": [
   "Ay, and a bold one, that dare look on that",
   "Which might appal the devil."
  ],
  "speech": [
   {
    "l": "O proper stuff!"
   },
   {
    "l": "This is the very painting of your fear:"
   },
   {
    "l": "This is the air-drawn dagger which you said,"
   },
   {
    "l": "Led you to Duncan. O, these flaws, and starts"
   },
   {
    "l": "(Impostors to true fear), would well become"
   },
   {
    "l": "A woman's story at a winter's fire,"
   },
   {
    "l": "Authoris'd by her grandam. Shame itself!"
   },
   {
    "l": "Why do you make such faces? When all's done,"
   },
   {
    "l": "You look but on a stool."
   }
  ],
  "word": "O"
 },
 {
  "act": "3",
  "sc": "4",
  "n": 73,
  "who": "Macbeth",
  "cue": [
   "If charnel houses and our graves must send",
   "Those that we bury back, our monuments",
   "Shall be the maws of kites."
  ],
  "speech": [
   {
    "l": "What, quite unmann'd in folly?"
   }
  ],
  "word": "What"
 },
 {
  "act": "3",
  "sc": "4",
  "n": 75,
  "who": "Macbeth",
  "cue": [
   "If I stand here, I saw him."
  ],
  "speech": [
   {
    "l": "Fie, for shame!"
   }
  ],
  "word": "Fie"
 },
 {
  "act": "3",
  "sc": "4",
  "n": 84,
  "who": "Macbeth",
  "cue": [
   "With twenty mortal murders on their crowns,",
   "And push us from our stools. This is more strange",
   "Than such a murder is."
  ],
  "speech": [
   {
    "l": "My worthy lord,"
   },
   {
    "l": "Your noble friends do lack you."
   }
  ],
  "word": "My"
 },
 {
  "act": "3",
  "sc": "4",
  "n": 98,
  "who": "Macbeth",
  "cue": [
   "Thy bones are marrowless, thy blood is cold;",
   "Thou hast no speculation in those eyes",
   "Which thou dost glare with!"
  ],
  "speech": [
   {
    "l": "Think of this, good peers,"
   },
   {
    "l": "But as a thing of custom: 'tis no other,"
   },
   {
    "l": "Only it spoils the pleasure of the time."
   }
  ],
  "word": "Think"
 },
 {
  "act": "3",
  "sc": "4",
  "n": 108,
  "who": "Macbeth",
  "cue": [
   "Why, so;--being gone,",
   "I am a man again.--Pray you, sit still."
  ],
  "speech": [
   {
    "l": "You have displaced the mirth, broke the good meeting"
   },
   {
    "l": "With most admir'd disorder."
   }
  ],
  "word": "You"
 },
 {
  "act": "3",
  "sc": "4",
  "n": 117,
  "who": "Ross",
  "cue": [
   "What sights, my lord?"
  ],
  "speech": [
   {
    "l": "I pray you, speak not; he grows worse and worse;"
   },
   {
    "l": "Question enrages him. At once, good night:--"
   },
   {
    "l": "Stand not upon the order of your going,"
   },
   {
    "l": "But go at once."
   }
  ],
  "word": "I"
 },
 {
  "act": "3",
  "sc": "4",
  "n": 122,
  "who": "Lennox",
  "cue": [
   "Good night; and better health",
   "Attend his Majesty!"
  ],
  "speech": [
   {
    "l": "A kind good night to all!"
   }
  ],
  "word": "A"
 },
 {
  "act": "3",
  "sc": "4",
  "n": 126,
  "who": "Macbeth",
  "cue": [
   "Augurs, and understood relations, have",
   "By magot-pies, and choughs, and rooks, brought forth",
   "The secret'st man of blood.--What is the night?"
  ],
  "speech": [
   {
    "l": "Almost at odds with morning, which is which."
   }
  ],
  "word": "Almost"
 },
 {
  "act": "3",
  "sc": "4",
  "n": 128,
  "who": "Macbeth",
  "cue": [
   "How say'st thou, that Macduff denies his person",
   "At our great bidding?"
  ],
  "speech": [
   {
    "l": "Did you send to him, sir?"
   }
  ],
  "word": "Did"
 },
 {
  "act": "3",
  "sc": "4",
  "n": 140,
  "who": "Macbeth",
  "cue": [
   "Returning were as tedious as go o'er.",
   "Strange things I have in head, that will to hand,",
   "Which must be acted ere they may be scann'd."
  ],
  "speech": [
   {
    "l": "You lack the season of all natures, sleep."
   }
  ],
  "word": "You"
 },
 {
  "act": "5",
  "sc": "1",
  "n": 35,
  "who": "Gentlewoman",
  "cue": [
   "It is an accustomed action with her, to seem thus washing her hands. I",
   "have known her continue in this a quarter of an hour."
  ],
  "speech": [
   {
    "l": "Yet here's a spot."
   }
  ],
  "word": "Yet"
 },
 {
  "act": "5",
  "sc": "1",
  "n": 39,
  "who": "Doctor",
  "cue": [
   "Hark, she speaks. I will set down what comes from her, to satisfy my",
   "remembrance the more strongly."
  ],
  "speech": [
   {
    "l": "Out, damned spot! out, I say! One; two. Why, then 'tis time to do't."
   },
   {
    "l": "Hell is murky! Fie, my lord, fie! a soldier, and afeard? What need we"
   },
   {
    "l": "fear who knows it, when none can call our power to account? Yet who"
   },
   {
    "l": "would have thought the old man to have had so much blood in him?"
   }
  ],
  "word": "Out"
 },
 {
  "act": "5",
  "sc": "1",
  "n": 47,
  "who": "Doctor",
  "cue": [
   "Do you mark that?"
  ],
  "speech": [
   {
    "l": "The Thane of Fife had a wife. Where is she now?--What, will these hands"
   },
   {
    "l": "ne'er be clean? No more o' that, my lord, no more o' that: you mar all"
   },
   {
    "l": "with this starting."
   }
  ],
  "word": "The"
 },
 {
  "act": "5",
  "sc": "1",
  "n": 57,
  "who": "Gentlewoman",
  "cue": [
   "She has spoke what she should not, I am sure of that: heaven knows what",
   "she has known."
  ],
  "speech": [
   {
    "l": "Here's the smell of the blood still: all the perfumes of Arabia will"
   },
   {
    "l": "not sweeten this little hand. Oh, oh, oh!"
   }
  ],
  "word": "Here's"
 },
 {
  "act": "5",
  "sc": "1",
  "n": 66,
  "who": "Doctor",
  "cue": [
   "This disease is beyond my practice: yet I have known those which have",
   "walked in their sleep, who have died holily in their beds."
  ],
  "speech": [
   {
    "l": "Wash your hands, put on your nightgown; look not so pale. I tell you"
   },
   {
    "l": "yet again, Banquo's buried; he cannot come out on's grave."
   }
  ],
  "word": "Wash"
 },
 {
  "act": "5",
  "sc": "1",
  "n": 69,
  "who": "Doctor",
  "cue": [
   "Even so?"
  ],
  "speech": [
   {
    "l": "To bed, to bed. There's knocking at the gate. Come, come, come, come,"
   },
   {
    "l": "give me your hand. What's done cannot be undone. To bed, to bed, to"
   },
   {
    "l": "bed."
   }
  ],
  "word": "To"
 }
];
